#define F(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
};
#define JIP(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
    jip = 1; \
};

#define ANYONE 0
#define CLIENT 1
#define SERVER 2
#define HC HC_Life

class CfgRemoteExec {
    class Functions {
        mode = 1;
        jip = 1;
		
		#include "The-Programmer\theprogrammer_remoteExec_master.cpp"
        /* Client only functions */
        F(ANZUS_fnc_AAN,CLIENT)
        F(ANZUS_fnc_AANBank,CLIENT)
        F(ANZUS_fnc_secondAANnews,CLIENT)
        F(ANZUS_fnc_addVehicle2Chain,CLIENT)
        F(ANZUS_fnc_adminID,CLIENT)
        F(ANZUS_fnc_adminInfo,CLIENT)
        F(ANZUS_fnc_bountyReceive,CLIENT)
        F(ANZUS_fnc_copSearch,CLIENT)
		    F(ANZUS_fnc_medBDinit,CLIENT)
        JIP(ANZUS_fnc_copSiren,CLIENT)
        F(ANZUS_fnc_freezePlayer,CLIENT)
        F(ANZUS_fnc_gangDisbanded,CLIENT)
        F(ANZUS_fnc_gangInvite,CLIENT)
        F(ANZUS_fnc_garageRefund,CLIENT)
        F(ANZUS_fnc_giveDiff,CLIENT)
        F(ANZUS_fnc_DohideObj,CLIENT)
		    F(life_fnc_bloodDrive,CLIENT)
        F(ANZUS_fnc_impoundMenu,CLIENT)
        F(ANZUS_fnc_initjail,CLIENT)
        F(ANZUS_fnc_impresionPlayer,CLIENT)
        F(ANZUS_fnc_knockedOut,CLIENT)
        F(ANZUS_fnc_licenseCheck,CLIENT)
        F(ANZUS_fnc_licensesRead,CLIENT)
        F(ANZUS_fnc_lightupHouse,CLIENT)
        F(ANZUS_fnc_medicRequest,CLIENT)
        JIP(ANZUS_fnc_medicSiren,CLIENT)
        F(ANZUS_fnc_moveIn,CLIENT)
        F(ANZUS_fnc_MepickupItem,CLIENT)
        F(ANZUS_fnc_pickupMoney,CLIENT)
        F(ANZUS_fnc_removeLicenses,CLIENT)
        F(ANZUS_fnc_restrainclientforcop,CLIENT)


		
        F(ANZUS_fnc_Merevived,CLIENT)
        F(ANZUS_fnc_robPerson,CLIENT)
        F(ANZUS_fnc_robReceive,CLIENT)
        F(ANZUS_fnc_searchClient,CLIENT)
        F(ANZUS_fnc_seizeClient,CLIENT)
        F(anzus_fnc_spikeStripEffect,CLIENT)
        F(ANZUS_fnc_tazeSound,CLIENT)
        F(ANZUS_fnc_ticketPrompt,CLIENT)
        F(ANZUS_fnc_vehicleAnimate,CLIENT)
        F(ANZUS_fnc_wireTransfer,CLIENT)
        F(ANZUS_fnc_dataQuery,CLIENT)
        F(ANZUS_fnc_insertPlayerInfo,CLIENT)
        F(ANZUS_fnc_requestReceived,CLIENT)
        F(ANZUS_fnc_updateRequest,CLIENT)
        F(TON_fnc_clientGangKick,CLIENT)
        F(TON_fnc_clientGangLeader,CLIENT)
        F(TON_fnc_clientGangLeft,CLIENT)
        F(TON_fnc_clientGetKey,CLIENT)
        F(TON_fnc_clientMessage,CLIENT)
        F(TON_fnc_player_query,CLIENT)
        F(ANZUS_fnc_killfeed,CLIENT)
        F(ANZUS_fnc_radArea,CLIENT)
        F(ANZUS_fnc_placedrill,CLIENT)
        F(ANZUS_fnc_typemarkers,CLIENT)
        F(ANZUS_fnc_spawndrill,CLIENT)
        F(ANZUS_fnc_cprrevived,CLIENT)
        F(ANZUS_fnc_tieing,CLIENT)
		    F(ANZUS_fnc_tieingb,CLIENT)
		    F(ANZUS_fnc_gagged,CLIENT)
        F(ANZUS_fnc_backupCall,CLIENT)
        F(ANZUS_fnc_removeWeaponAction,CLIENT)
        F(ANZUS_fnc_GangCreated,CLIENT)
        F(ANZUS_fnc_writeDeathScreen, CLIENT)
        F(ANZUS_fnc_giveItemReturn,CLIENT)
        F(ANZUS_fnc_receiveitem,CLIENT)
        F(AnzusLife_PropertyTaxPay,CLIENT)
        F(AnzusLife_BuyTicket,CLIENT)
        F(AnzusLife_TazedGangPerk,CLIENT)
        F(AnzusLife_KillHostage,CLIENT)
        F(ANZUS_fnc_receiveWarrants,CLIENT)
        F(AnzusLife_GetSetName,CLIENT)
        F(AnzusLife_SaveName,CLIENT)
        F(AnzusLife_PlayerStabilized,CLIENT)
        F(AnzusLife_DenyFee,CLIENT)
        F(xiyECYLNxrKhXypAac,CLIENT)
        F(ANZUS_fnc_contactCheck,CLIENT)
        F(AH_PlayerLoad,CLIENT)

        /* Server only functions */
        F(AH_LogInterface, SERVER)
        F(ANZUS_fnc_insertRequest,SERVER)
        F(ANZUS_fnc_queryRequest,SERVER)
        F(ANZUS_fnc_updatePartialServer,SERVER)
        F(ANZUS_fnc_updateRequestServer,SERVER)
        F(ANZUS_fnc_jailSys,SERVER)
        F(TON_fnc_addContainer,SERVER)
        F(TON_fnc_addHouse,SERVER)
        F(TON_fnc_chopShopSell,SERVER)
        F(TON_fnc_anzusinsertlog,SERVER)
        F(TON_fnc_cleanupRequest,SERVER)
        F(TON_fnc_deleteDBContainer,SERVER)
        F(TON_fnc_getID,SERVER)
        F(TON_fnc_getVehicles,SERVER)
        F(TON_fnc_timers,SERVER)
        F(TON_fnc_insureVehicle,SERVER)
        F(TON_fnc_insertGang,SERVER)
        F(TON_fnc_keyManagement,SERVER)
        F(TON_fnc_pickupAction,SERVER)
        F(TON_fnc_removeGang,SERVER)
        F(TON_fnc_sellHouse,SERVER)
        F(TON_fnc_sellHouseContainer,SERVER)
        F(TON_fnc_spawnVehicle,SERVER)
        F(TON_fnc_spikeStrip,SERVER)
        F(TON_fnc_updateGang,SERVER)
        F(TON_fnc_updateHouseContainers,SERVER)
        F(TON_fnc_updateHouseTrunk,SERVER)
        F(TON_fnc_vehicleCreate,SERVER)
        F(TON_fnc_vehicleDelete,SERVER)
        F(TON_fnc_vehicleStore,SERVER)
        F(ANZUS_fnc_saveConviction,SERVER)
        F(TON_fnc_vehicleUpdate,SERVER)
        F(TON_fnc_houseGarage,SERVER)
        F(TON_fnc_insureCar,SERVER)
        F(serverVehicleStore,SERVER)
        F(ANZUS_fnc_addWarrantsServ,SERVER)
        F(ANZUS_fnc_delWarrantsServ,SERVER)
        F(ANZUS_fnc_queryWarrantsServ,SERVER)
        F(ANZUS_fnc_jailSaveTime,SERVER)
        F(AnzusLife_ImpoundVehicleServ,SERVER)
        F(AnzusLife_UpdateLevel,SERVER)
        F(AnzusLife_PropertyTaxCheck,SERVER)
        F(AnzusLife_PropertyTaxPayServ,SERVER)
        F(AnzusLife_PropertyTaxCheckLogin,SERVER)
        F(AnzusLife_WealthTaxCheckLogin,SERVER)
        F(AnzusLife_CheckTick,SERVER)
        F(AnzusLife_BuyTicketServ,SERVER)
        F(AnzusLife_UnlockTask,SERVER)
        F(AnzusLife_Lib_CreateMarker,SERVER)
        F(AnzusLife_Lib_ChangeGangMarker,SERVER)
        F(AnzusLife_AC_SetDamage,SERVER)
        F(AnzusLife_AC_SetDamageObject,SERVER)
        F(AnzusLife_AC_OpenTrunk,SERVER)
        F(AnzusLife_AC_CloseTrunk,SERVER)
        F(AnzusLife_ReciveGangProfit,SERVER)
        F(AnzusLife_RunWeed,SERVER)
        F(AnzusLife_PlaceItem,SERVER)
        F(AnzusLife_ItemBought,SERVER)
        F(AnzusLife_TotalItems,SERVER)
        F(AH_KeyCheck,SERVER)
        F(AnzusLife_Lib_ChangeGangMarkerColor,SERVER)
        JIP(mav_ttm_fnc_loadFromDatabase,SERVER)
        JIP(mav_ttm_fnc_updateDatabaseEntry,SERVER)
		
		//PHONE
		F(TON_fnc_managePhone,SERVER)
		F(TON_fnc_manageRadio,SERVER)
		
		F(ANZUS_fnc_cell_call,CLIENT)  	
		F(ANZUS_fnc_phoneCall,CLIENT)  			
		F(ANZUS_fnc_phoneEnd,CLIENT)  	
		F(ANZUS_fnc_MP,CLIENT)  	
		F(ANZUS_fnc_cleanName,CLIENT) 
		F(ANZUS_fnc_setupEVH,CLIENT)
        /* Functions for everyone */

        F(ANZUS_fnc_playsound,ANYONE)
		
		F(BIS_fnc_dynamicGroups,ANYONE)

        F(BIS_fnc_effectKilledAirDestruction,ANYONE)
        F(BIS_fnc_effectKilledSecondaries,ANYONE)
        F(ANZUS_fnc_animSync,ANYONE)
        F(ANZUS_fnc_broadcast,ANYONE)
        F(ANZUS_fnc_colorVehicle,ANYONE)
        F(ANZUS_fnc_flashbang,ANYONE)
        F(ANZUS_fnc_lockVehicle,ANYONE)
        F(ANZUS_fnc_pulloutVeh,ANYONE)
        F(ANZUS_fnc_setvehiclefuel,ANYONE)
        F(ANZUS_fnc_simDisable,ANYONE)
        F(SPY_fnc_notifyAdmins,ANYONE)
        F(ANZUS_fnc_setEngineHit,ANYONE)
        F(ANZUS_fnc_notificationSystem,ANYONE)
        F(ANZUS_fnc_hudUpdate,ANYONE)
        F(ANZUS_fnc_crashTackled,ANYONE)
        F(ANZUS_fnc_GangInviteReceived,ANYONE)
        F(ANZUS_fnc_GangNewLeader,ANYONE)
        F(ANZUS_fnc_loadGangMenu,ANYONE)
        F(ANZUS_fnc_getKey,ANYONE)
        F(ANZUS_fnc_ReceiveMoney,ANYONE)
        F(ANZUS_fnc_SetupQueryNumber,ANYONE)
        F(ANZUS_fnc_Server_MessageRelay,ANYONE)
        F(ANZUS_fnc_ReceiveEMessage, ANYONE)
        F(AnzusLife_NotifyCheckpoint, ANYONE)
		    F(ANZUS_fnc_createdarter,ANYONE)
        F(ANZUS_fnc_accessCodeTimeOut,ANYONE)
        F(ANZUS_fnc_hackComputer,ANYONE)
        F(ANZUS_fnc_hackMainframe,ANYONE)
        F(ANZUS_fnc_removeUSBKeys,ANYONE)
        F(ANZUS_fnc_resetCommandCodes,ANYONE)
    };

    class Commands {
        mode = 1;
        jip = 0;

        F(setunitloadout,CLIENT)
        F(addHandgunItem,ANYONE)
        F(addMagazine,ANYONE)
        F(addPrimaryWeaponItem,ANYONE)
        F(addWeapon,ANYONE)
        F(setFuel,ANYONE)
        F(playSound,CLIENT)
        F(say3D,CLIENT)
        F(hideobjectglobal,ANYONE)
    };
};
