/*

	Filename: 	fn_preInit.sqf
	Project: 	Sunrise Life
	Author:		Sunrise Team
	Steam:		Sunrise Team


*/
private _headerNoDebug = '
	private _fnc_scriptNameParent = if (isNil "_fnc_scriptName") then {"%1"} else {_fnc_scriptName};
	private _fnc_scriptName = "%1";
	scriptName _fnc_scriptName;
';
private _is_dev = serverName isEqualTo "test";
{
	_script = _x select 0;
	_code = if (_is_dev) then {compile (format[_headerNoDebug,_script] + preprocessFileLineNumbers (_x select 1))} else {compileFinal (format[_headerNoDebug,_script] + preprocessFileLineNumbers (_x select 1))};
	missionNamespace setVariable [_script, _code];
} forEach
[ 
	['SunriseServer_system_vehicleAdacRecolor', 'SunriseServer\code\adac\SunriseServer_system_vehicleAdacRecolor.sqf'], 
	['SunriseServer_system_vehicleAdacRematerial', 'SunriseServer\code\adac\SunriseServer_system_vehicleAdacRematerial.sqf'], 
	['SunriseServer_system_vehicleAdacUpdate', 'SunriseServer\code\adac\SunriseServer_system_vehicleAdacUpdate.sqf'], 
	['SunriseServer_system_cleanup', 'SunriseServer\code\clean\SunriseServer_system_cleanup.sqf'], 
	['SunriseServer_system_monitor', 'SunriseServer\code\clean\SunriseServer_system_monitor.sqf'], 
	['SunriseServer_system_objectClean', 'SunriseServer\code\clean\SunriseServer_system_objectClean.sqf'], 
	['SunriseServer_system_updataGovern', 'SunriseServer\code\economy\SunriseServer_system_updataGovern.sqf'], 
	['SunriseServer_system_updateExp', 'SunriseServer\code\Experience\SunriseServer_system_updateExp.sqf'], 
	['SunriseServer_factory_order', 'SunriseServer\code\Factories\SunriseServer_factory_order.sqf'], 
	['SunriseServer_factory_processOrders', 'SunriseServer\code\Factories\SunriseServer_factory_processOrders.sqf'], 
	['SunriseServer_factory_updateFactories', 'SunriseServer\code\Factories\SunriseServer_factory_updateFactories.sqf'], 
	['SunriseServer_factory_vehicleLoad', 'SunriseServer\code\Factories\SunriseServer_factory_vehicleLoad.sqf'], 
	['SunriseServer_factory_vehicleProcess', 'SunriseServer\code\Factories\SunriseServer_factory_vehicleProcess.sqf'], 
	['SunriseServer_system_copGoOnDuty', 'SunriseServer\code\gangs\SunriseServer_system_copGoOnDuty.sqf'], 
	['SunriseServer_system_dutyGearLoad', 'SunriseServer\code\gangs\SunriseServer_system_dutyGearLoad.sqf'], 
	['SunriseServer_system_dutyGearSave', 'SunriseServer\code\gangs\SunriseServer_system_dutyGearSave.sqf'], 
	['SunriseServer_system_getOffline', 'SunriseServer\code\gangs\SunriseServer_system_getOffline.sqf'], 
	['SunriseServer_system_initFractionGang', 'SunriseServer\code\gangs\SunriseServer_system_initFractionGang.sqf'], 
	['SunriseServer_system_initFractionGangs', 'SunriseServer\code\gangs\SunriseServer_system_initFractionGangs.sqf'], 
	['SunriseServer_system_initGang', 'SunriseServer\code\gangs\SunriseServer_system_initGang.sqf'], 
	['SunriseServer_system_insertGang', 'SunriseServer\code\gangs\SunriseServer_system_insertGang.sqf'], 
	['SunriseServer_system_kickOffline', 'SunriseServer\code\gangs\SunriseServer_system_kickOffline.sqf'], 
	['SunriseServer_system_medGoOnDuty', 'SunriseServer\code\gangs\SunriseServer_system_medGoOnDuty.sqf'], 
	['SunriseServer_system_queryPlayerGang', 'SunriseServer\code\gangs\SunriseServer_system_queryPlayerGang.sqf'], 
	['SunriseServer_system_removeGang', 'SunriseServer\code\gangs\SunriseServer_system_removeGang.sqf'], 
	['SunriseServer_system_updateGang', 'SunriseServer\code\gangs\SunriseServer_system_updateGang.sqf'], 
	['SunriseServer_system_updateGangBank', 'SunriseServer\code\gangs\SunriseServer_system_updateGangBank.sqf'], 
	['SunriseServer_system_updateGangTrunks', 'SunriseServer\code\gangs\SunriseServer_system_updateGangTrunks.sqf'], 
	['SunriseServer_system_updateGangWarPoints', 'SunriseServer\code\gangs\SunriseServer_system_updateGangWarPoints.sqf'], 
	['SunriseServer_system_changeVehicleServerMap', 'SunriseServer\code\garage\SunriseServer_system_changeVehicleServerMap.sqf'], 
	['SunriseServer_system_chopShopOwn', 'SunriseServer\code\garage\SunriseServer_system_chopShopOwn.sqf'], 
	['SunriseServer_system_chopShopSell', 'SunriseServer\code\garage\SunriseServer_system_chopShopSell.sqf'], 
	['SunriseServer_system_getVehicles', 'SunriseServer\code\garage\SunriseServer_system_getVehicles.sqf'], 
	['SunriseServer_system_handleVehicle', 'SunriseServer\code\garage\SunriseServer_system_handleVehicle.sqf'], 
	['SunriseServer_system_initVehicleRestart', 'SunriseServer\code\garage\SunriseServer_system_initVehicleRestart.sqf'], 
	['SunriseServer_system_insurancePayRequest', 'SunriseServer\code\garage\SunriseServer_system_insurancePayRequest.sqf'], 
	['SunriseServer_system_saveVehicleRestart', 'SunriseServer\code\garage\SunriseServer_system_saveVehicleRestart.sqf'], 
	['SunriseServer_system_spawnVehicle', 'SunriseServer\code\garage\SunriseServer_system_spawnVehicle.sqf'], 
	['SunriseServer_system_vehicleCreate', 'SunriseServer\code\garage\SunriseServer_system_vehicleCreate.sqf'], 
	['SunriseServer_system_vehicleParkingPay', 'SunriseServer\code\garage\SunriseServer_system_vehicleParkingPay.sqf'], 
	['SunriseServer_system_vehicleParkingStore', 'SunriseServer\code\garage\SunriseServer_system_vehicleParkingStore.sqf'], 
	['SunriseServer_system_vehicleSell', 'SunriseServer\code\garage\SunriseServer_system_vehicleSell.sqf'], 
	['SunriseServer_system_vehicleStore', 'SunriseServer\code\garage\SunriseServer_system_vehicleStore.sqf'], 
	['SunriseServer_system_vehicleUpdate', 'SunriseServer\code\garage\SunriseServer_system_vehicleUpdate.sqf'], 
	['SunriseServer_system_vehSearch', 'SunriseServer\code\garage\SunriseServer_system_vehSearch.sqf'], 
	['SunriseServer_system_serverBank', 'SunriseServer\code\gover\SunriseServer_system_serverBank.sqf'], 
	['SunriseServer_system_submitCandidate', 'SunriseServer\code\gover\SunriseServer_system_submitCandidate.sqf'], 
	['SunriseServer_system_vote', 'SunriseServer\code\gover\SunriseServer_system_vote.sqf'], 
	//['SunriseServer_system_hazardSpawnLoot', 'SunriseServer\code\hazard\SunriseServer_system_hazardSpawnLoot.sqf'], 
	//['SunriseServer_system_hazardZone', 'SunriseServer\code\hazard\SunriseServer_system_hazardZone.sqf'], 
	['SunriseServer_system_addHouse', 'SunriseServer\code\housing\SunriseServer_system_addHouse.sqf'], 
	['SunriseServer_system_CheckHouse', 'SunriseServer\code\housing\SunriseServer_system_CheckHouse.sqf'], 
	['SunriseServer_system_fetchPlayerHouses', 'SunriseServer\code\housing\SunriseServer_system_fetchPlayerHouses.sqf'], 
	['SunriseServer_system_initHouses', 'SunriseServer\code\housing\SunriseServer_system_initHouses.sqf'], 
	['SunriseServer_system_reqHouseInfo', 'SunriseServer\code\housing\SunriseServer_system_reqHouseInfo.sqf'], 
	['SunriseServer_system_sellHouse', 'SunriseServer\code\housing\SunriseServer_system_sellHouse.sqf'], 
	['SunriseServer_system_unlockHouseContainer', 'SunriseServer\code\housing\SunriseServer_system_unlockHouseContainer.sqf'], 
	['SunriseServer_system_updateHouseContainers', 'SunriseServer\code\housing\SunriseServer_system_updateHouseContainers.sqf'], 
	['SunriseServer_system_updateHouseRent', 'SunriseServer\code\housing\SunriseServer_system_updateHouseRent.sqf'], 
	['SunriseServer_system_updateHouseSecurity', 'SunriseServer\code\housing\SunriseServer_system_updateHouseSecurity.sqf'], 
	['SunriseServer_system_updateHouseSlots', 'SunriseServer\code\housing\SunriseServer_system_updateHouseSlots.sqf'], 
	['SunriseServer_system_updateHouseTrunk', 'SunriseServer\code\housing\SunriseServer_system_updateHouseTrunk.sqf'], 
	['SunriseServer_system_jailSys', 'SunriseServer\code\jail\SunriseServer_system_jailSys.sqf'], 
	['SunriseServer_system_wantedUpdateJailTime', 'SunriseServer\code\jail\SunriseServer_system_wantedUpdateJailTime.sqf'], 
	['SunriseServer_market_buy', 'SunriseServer\code\market\SunriseServer_market_buy.sqf'], 
	['SunriseServer_market_delete', 'SunriseServer\code\market\SunriseServer_market_delete.sqf'], 
	['SunriseServer_market_init', 'SunriseServer\code\market\SunriseServer_market_init.sqf'], 
	['SunriseServer_market_sell', 'SunriseServer\code\market\SunriseServer_market_sell.sqf'], 
	['SunriseServer_market_takeBack', 'SunriseServer\code\market\SunriseServer_market_takeBack.sqf'], 
	['SunriseServer_database_ban', 'SunriseServer\code\mysql\SunriseServer_database_ban.sqf'], 
	['SunriseServer_database_fireAndForget', 'SunriseServer\code\mysql\SunriseServer_database_fireAndForget.sqf'], 
	['SunriseServer_database_handleBig', 'SunriseServer\code\mysql\SunriseServer_database_handleBig.sqf'], 
	['SunriseServer_database_insertRequest', 'SunriseServer\code\mysql\SunriseServer_database_insertRequest.sqf'], 
	['SunriseServer_database_insertSingle', 'SunriseServer\code\mysql\SunriseServer_database_insertSingle.sqf'], 
	['SunriseServer_database_numberSafe', 'SunriseServer\code\mysql\SunriseServer_database_numberSafe.sqf'], 
	['SunriseServer_database_queryRequest', 'SunriseServer\code\mysql\SunriseServer_database_queryRequest.sqf'], 
	['SunriseServer_database_selectFull', 'SunriseServer\code\mysql\SunriseServer_database_selectFull.sqf'], 
	['SunriseServer_database_selectSingle', 'SunriseServer\code\mysql\SunriseServer_database_selectSingle.sqf'], 
	['SunriseServer_database_selectSingleField', 'SunriseServer\code\mysql\SunriseServer_database_selectSingleField.sqf'], 
	['SunriseServer_database_strip', 'SunriseServer\code\mysql\SunriseServer_database_strip.sqf'], 
	['SunriseServer_database_updateMoney', 'SunriseServer\code\mysql\SunriseServer_database_updateMoney.sqf'], 
	['SunriseServer_database_updatePartial', 'SunriseServer\code\mysql\SunriseServer_database_updatePartial.sqf'], 
	['SunriseServer_database_updatePlayerIndCfg', 'SunriseServer\code\mysql\SunriseServer_database_updatePlayerIndCfg.sqf'], 
	['SunriseServer_database_updateRequest', 'SunriseServer\code\mysql\SunriseServer_database_updateRequest.sqf'], 
	['SunriseServer_system_pdatabaseDelete', 'SunriseServer\code\policedatabase\SunriseServer_system_pdatabaseDelete.sqf'], 
	['SunriseServer_system_pdatabaseFetch', 'SunriseServer\code\policedatabase\SunriseServer_system_pdatabaseFetch.sqf'], 
	['SunriseServer_system_pdatabaseManage', 'SunriseServer\code\policedatabase\SunriseServer_system_pdatabaseManage.sqf'], 
	['SunriseServer_system_capturePay', 'SunriseServer\code\rescapture\SunriseServer_system_capturePay.sqf'], 
	['SunriseServer_system_endBattle', 'SunriseServer\code\rescapture\SunriseServer_system_endBattle.sqf'], 
	['SunriseServer_system_initBattle', 'SunriseServer\code\rescapture\SunriseServer_system_initBattle.sqf'], 
	['SunriseServer_system_initCaptures', 'SunriseServer\code\rescapture\SunriseServer_system_initCaptures.sqf'], 
	['SunriseServer_system_loadEnabledCaptures', 'SunriseServer\code\rescapture\SunriseServer_system_loadEnabledCaptures.sqf'], 
	['SunriseServer_system_manageApplicants', 'SunriseServer\code\rescapture\SunriseServer_system_manageApplicants.sqf'], 
	['SunriseServer_system_clothingShopBuy', 'SunriseServer\code\Shops\SunriseServer_system_clothingShopBuy.sqf'], 
	['SunriseServer_system_clothingShopOpen', 'SunriseServer\code\Shops\SunriseServer_system_clothingShopOpen.sqf'], 
	['SunriseServer_system_handleShops', 'SunriseServer\code\Shops\SunriseServer_system_handleShops.sqf'], 
	['SunriseServer_system_vehicleShopOpen', 'SunriseServer\code\Shops\SunriseServer_system_vehicleShopOpen.sqf'], 
	['SunriseServer_system_weaponShopBuy', 'SunriseServer\code\Shops\SunriseServer_system_weaponShopBuy.sqf'], 
	['SunriseServer_system_weaponShopOpen', 'SunriseServer\code\Shops\SunriseServer_system_weaponShopOpen.sqf'], 
	['SunriseServer_carsharing_stop', 'SunriseServer\code\systems\SunriseServer_carsharing_stop.sqf'], 
	['SunriseServer_pouch_openPouch', 'SunriseServer\code\systems\SunriseServer_pouch_openPouch.sqf'], 
	['SunriseServer_pouch_updatePouch', 'SunriseServer\code\systems\SunriseServer_pouch_updatePouch.sqf'], 
	['SunriseServer_system_battleground', 'SunriseServer\code\systems\SunriseServer_system_battleground.sqf'], 
	['SunriseServer_system_becomeDispatcher', 'SunriseServer\code\systems\SunriseServer_system_becomeDispatcher.sqf'], 
	['SunriseServer_system_changePlayerServerMap', 'SunriseServer\code\systems\SunriseServer_system_changePlayerServerMap.sqf'], 
	['SunriseServer_system_checkConnection', 'SunriseServer\code\systems\SunriseServer_system_checkConnection.sqf'], 
	['SunriseServer_system_clientConnect', 'SunriseServer\code\systems\SunriseServer_system_clientConnect.sqf'], 
	['SunriseServer_system_clientDisconnect', 'SunriseServer\code\systems\SunriseServer_system_clientDisconnect.sqf'], 
	['SunriseServer_system_clientEndmission', 'SunriseServer\code\systems\SunriseServer_system_clientEndmission.sqf'], 
	['SunriseServer_system_combatVehicleReq', 'SunriseServer\code\systems\SunriseServer_system_combatVehicleReq.sqf'], 
	['SunriseServer_system_copLeaveDuty', 'SunriseServer\code\systems\SunriseServer_system_copLeaveDuty.sqf'], 
	['SunriseServer_system_customLog', 'SunriseServer\code\systems\SunriseServer_system_customLog.sqf'], 
	['SunriseServer_system_federalUpdate', 'SunriseServer\code\systems\SunriseServer_system_federalUpdate.sqf'], 
	['SunriseServer_system_getHousePos', 'SunriseServer\code\systems\SunriseServer_system_getHousePos.sqf'], 
	['SunriseServer_system_getID', 'SunriseServer\code\systems\SunriseServer_system_getID.sqf'], 
	['SunriseServer_system_getRestartTime', 'SunriseServer\code\systems\SunriseServer_system_getRestartTime.sqf'], 
	['SunriseServer_system_handleBlastingCharge', 'SunriseServer\code\systems\SunriseServer_system_handleBlastingCharge.sqf'], 
	['SunriseServer_system_huntingZone', 'SunriseServer\code\systems\SunriseServer_system_huntingZone.sqf'], 
	['SunriseServer_system_keyManagement', 'SunriseServer\code\systems\SunriseServer_system_keyManagement.sqf'], 
	['SunriseServer_system_log', 'SunriseServer\code\systems\SunriseServer_system_log.sqf'], 
	['SunriseServer_system_logSearch', 'SunriseServer\code\systems\SunriseServer_system_logSearch.sqf'], 
	['SunriseServer_system_medLeaveDuty', 'SunriseServer\code\systems\SunriseServer_system_medLeaveDuty.sqf'], 
	['SunriseServer_system_rcon', 'SunriseServer\code\systems\SunriseServer_system_rcon.sqf'], 
	['SunriseServer_system_recupKeyForHC', 'SunriseServer\code\systems\SunriseServer_system_recupKeyForHC.sqf'], 
	['SunriseServer_system_restart', 'SunriseServer\code\systems\SunriseServer_system_restart.sqf'], 
	['SunriseServer_system_serverCommand', 'SunriseServer\code\systems\SunriseServer_system_serverCommand.sqf'], 
	['SunriseServer_system_spikeStrip', 'SunriseServer\code\systems\SunriseServer_system_spikeStrip.sqf'], 
	['SunriseServer_system_transferOwnership', 'SunriseServer\code\systems\SunriseServer_system_transferOwnership.sqf'], 
	['SunriseServer_system_turtleZone', 'SunriseServer\code\systems\SunriseServer_system_turtleZone.sqf'], 
	['SunriseServer_system_vehicleServiceSave', 'SunriseServer\code\systems\SunriseServer_system_vehicleServiceSave.sqf'], 
	['SunriseServer_system_wantedAdd', 'SunriseServer\code\wantedsystem\SunriseServer_system_wantedAdd.sqf'], 
	['SunriseServer_system_wantedBounty', 'SunriseServer\code\wantedsystem\SunriseServer_system_wantedBounty.sqf'], 
	['SunriseServer_system_wantedCheck', 'SunriseServer\code\wantedsystem\SunriseServer_system_wantedCheck.sqf'], 
	['SunriseServer_system_wantedFetch', 'SunriseServer\code\wantedsystem\SunriseServer_system_wantedFetch.sqf'], 
	['SunriseServer_system_wantedFetchMedic', 'SunriseServer\code\wantedsystem\SunriseServer_system_wantedFetchMedic.sqf'], 
	['SunriseServer_system_wantedKilledbyCop', 'SunriseServer\code\wantedsystem\SunriseServer_system_wantedKilledbyCop.sqf'], 
	['SunriseServer_system_wantedKnockedByCop', 'SunriseServer\code\wantedsystem\SunriseServer_system_wantedKnockedByCop.sqf'], 
	['SunriseServer_system_wantedPerson', 'SunriseServer\code\wantedsystem\SunriseServer_system_wantedPerson.sqf'], 
	['SunriseServer_system_wantedProfUpdate', 'SunriseServer\code\wantedsystem\SunriseServer_system_wantedProfUpdate.sqf'], 
	['SunriseServer_system_wantedRemove', 'SunriseServer\code\wantedsystem\SunriseServer_system_wantedRemove.sqf'], 
	['SunriseServer_system_addWarPoint', 'SunriseServer\code\warzon\SunriseServer_system_addWarPoint.sqf'], 
	['SunriseServer_system_removeWarPoint', 'SunriseServer\code\warzon\SunriseServer_system_removeWarPoint.sqf'],
	
	['SunriseServer_ltd_initshops', 'SunriseServer\code\ltd\SunriseServer_ltd_initshops.sqf'],
	['SunriseServer_ltd_regaction', 'SunriseServer\code\ltd\SunriseServer_ltd_regaction.sqf'],
	['SunriseServer_ltd_updateitemprice', 'SunriseServer\code\ltd\SunriseServer_ltd_updateitemprice.sqf'],
	['SunriseServer_ltd_updateitemshopdatabase', 'SunriseServer\code\ltd\SunriseServer_ltd_updateitemshopdatabase.sqf'],
	['SunriseServer_ltd_additemstoshop', 'SunriseServer\code\ltd\SunriseServer_ltd_additemstoshop.sqf'],
	['SunriseServer_ltd_additemtoshopdatabase', 'SunriseServer\code\ltd\SunriseServer_ltd_additemtoshopdatabase.sqf'],
	['SunriseServer_ltd_getallmoney', 'SunriseServer\code\ltd\SunriseServer_ltd_getallmoney.sqf'],
	['SunriseServer_ltd_getinfo', 'SunriseServer\code\ltd\SunriseServer_ltd_getinfo.sqf'],
	
	['SunriseServer_system_updataPrices', 'SunriseServer\code\economy\SunriseServer_system_updataPrices.sqf'],
	['SunriseServer_system_loadPrices', 'SunriseServer\code\economy\SunriseServer_system_loadPrices.sqf']
];

true