/*
*    ARRAY FORMAT:
*        0: STRING (Classname)
*        1: STRING (Display Name, leave as "" for default)
*        2: SCALAR (Price)
*        3: STRING (Conditions) - Must return boolean :
*            String can contain any amount of conditions, aslong as the entire
*            string returns a boolean. This allows you to check any levels, licenses etc,
*            in any combination. For example:
*                "call life_coplevel && license_civ_someLicense"
*            This will also let you call any other function.
*
*   Clothing classnames can be found here: https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Equipment
*   Backpacks/remaining classnames can be found here (TIP: Search page for "pack"): https://community.bistudio.com/wiki/Arma_3_CfgVehicles_EMPTY
*
*/
class Clothing {
    class bruce {
        title = "STR_Shops_C_Bruce";
        conditions = "";
        side = "";
        uniforms[] = {
          { "NONE", $STR_C_Remove_uniforms, 0, "" },
		        { "AG_TBIRENUniform", "新手镇服装", 300, "group player getVariable ['gang_id',-1] isEqualTo 332" },
    			{ "xs_mantiya", "法官专属制服", 500, "getPlayerUID player in ['76561199063859158','76561199014404395']",'76561198978158050'},
				{ "cg_strippers1", "", 30, "" },
    			{ "cg_mayan1", "", 30, "" },
    			{ "cg_loading1", "", 30, "" },
    			{ "cg_hearts1", "", 30, "" },
    			{ "cg_evolution1", "", 30, "" },
    			{ "cg_deeznuts1", "", 30, "" },
    			{ "cg_dad1", "", 30, "" },
    			{ "cg_awesome1", "", 30, "" },
    			{ "cg_turtles1", "", 30, "" },
    			{ "cg_pika1", "", 30, "" },
    			{ "cg_masterrace1", "", 30, "" },
    			{ "cg_lsd1", "", 30, "" },
    			{ "cg_lambo1", "", 30, "" },
    			{ "cg_kfc1", "", 30, "" },
    			{ "cg_homer1", "", 30, "" },
    			{ "cg_gamerepeat1", "", 30, "" },
    			{ "cg_gameover1", "", 30, "" },
    			{ "cg_fightclub1", "", 30, "" },
    			{ "cg_ferrari1", "", 30, "" },
    			{ "cg_ea1", "", 30, "" },
    			{ "cg_pepsi1", "", 30, "" },
    			{ "cg_mario1", "", 30, "" },
    			{ "cg_lego1", "", 30, "" },
    			{ "cg_burgerking1", "", 30, "" },
    			{ "cg_beats1", "", 30, "" },
    			{ "cg_wow1", "", 30, "" },
    			{ "cg_got1", "", 30, "" },
    			{ "cg_tupac1", "", 30, "" },
    			{ "cg_superman1", "", 30, "" },
    			{ "cg_peanut1", "", 30, "" },
    			{ "cg_nike1", "", 30, "" },
    			{ "cg_mtv1", "", 30, "" },
    			{ "cg_joker1", "", 30, "" },
    			{ "cg_jason1", "", 30, "" },
    			{ "cg_csgo1", "", 30, "" },
    			{ "cg_condoms1", "", 30, "" },
    			{ "cg_catvideos1", "", 30, "" },
    			{ "cg_bipolar1", "", 30, "" },
    			{ "cg_bb1", "", 30, "" },
    			{ "U_C_Poloshirt_Subway", "", 30, "" },
    			{ "UB_NRL_roosters_shirt", "", 30, "" },
    			{ "UB_NRL_rabbitohs_shirt", "", 30, "" },
    			{ "vvv_character_rock1", "", 70, "" },
    			{ "vvv_character_rock2", "", 70, "" },
    			{ "vvv_character_rock3", "", 70, "" },
    			{ "vvv_character_rock4", "", 70, "" },
    			{ "vvv_character_sport_1", "", 90, "" },
    			{ "vvv_character_sport_2", "", 90, "" },
    			{ "vvv_character_sport_3", "", 90, "" },
    			{ "vvv_character_sport_4", "", 90, "" },
    			{ "vvv_character_sport_5", "", 90, "" },
    			{ "vvv_character_sport_6", "", 90, "" },
    			{ "vvv_character_sport_7", "", 90, "" },
    			{ "vvv_character_sport_8", "", 90, "" },
    			{ "vvv_character_sport_9", "", 90, "" },
    			{ "vvv_character_sport_10", "", 90, "" },
    			{ "vvv_character_sport_11", "", 90, "" },
    			{ "vvv_character_sport_12", "", 90, "" },
    			{ "vvv_character_sport_13", "", 90, "" },
    			{ "vvv_traje_jackoy", "", 150, "" },
    			{ "vvv_traje_jackoy2", "", 150, "" },
    			{ "vvv_traje_jackoy3", "", 150, "" },
    			{ "vvv_traje_jackoy4", "", 150, "" },
    			{ "vvv_traje_jackoy5", "", 150, "" },
    			{ "vvv_traje_jackoy6", "", 150, "" },
    			{ "vvv_traje_jackoy7", "", 150, "" },
    			{ "vvv_traje_jackoy8", "", 150, "" },
    			{ "TRYK_shirts_BLK_PAD_RED2", "", 250, "" },
    			{ "TRYK_shirts_BLK_PAD_BLU3", "", 250, "" },
    			{ "TRYK_shirts_BLK_PAD_BLW", "", 250, "" },
    			{ "TRYK_shirts_BLK_PAD_BL", "", 250, "" },
    			{ "TRYK_shirts_BLK_PAD_BK", "", 250, "" },
    			{ "TRYK_shirts_DENIM_RED2_Sleeve", "", 250, "" },
    			{ "TRYK_shirts_DENIM_R_Sleeve", "", 250, "" },
    			{ "TRYK_shirts_DENIM_BWH_Sleeve", "", 250, "" },
    			{ "TRYK_shirts_DENIM_BL_Sleeve", "", 250, "" },
    			{ "TRYK_shirts_DENIM_BK_Sleeve", "", 250, "" },
    			{ "TRYK_shirts_DENIM_ylb_Sleeve", "", 250, "" },
    			{ "TRYK_shirts_DENIM_ylb", "", 250, "" },
    			{ "TRYK_shirts_DENIM_RED2", "", 250, "" },
    			{ "TRYK_shirts_DENIM_R", "", 250, "" },
    			{ "TRYK_shirts_DENIM_BL", "", 250, "" },
    			{ "KAEL_SUITS_BR_F12", "", 500, "" },
    			{ "KAEL_SUITS_BLK_F", "", 500, "" },
    			{ "KAEL_SUITS_BR_F8", "", 500, "" },
    			{ "KAEL_SUITS_BR_F11", "", 500, "" },
    			{ "KAEL_SUITS_BR_F10", "", 500, "" },
    			{ "KAEL_SUITS_BR_F7", "", 500, "" },
    			{ "KAEL_SUITS_BR_F6", "", 500, "" },
    			{ "KAEL_SUITS_BR_F5", "", 500, "" },
    			{ "KAEL_SUITS_BR_F9", "", 500, "" },
    			{ "KAEL_SUITS_BR_F13", "", 500, "" },
    			{ "KAEL_SUITS_BR_F14", "", 500, "" },
    			{ "EF_HM_LPBL2", "Female Clothing", 100, "" },
    			{ "EF_HM_LPB2", "Female Clothing", 100, "" },
    			{ "EF_HM_LPBR2", "Female Clothing", 100, "" },
    			{ "EF_FEM_4_2LPBP", "Female Clothing", 100, "" },
    			{ "EF_FEM_3_3LPBL", "Female Clothing", 100, "" },
    			{ "EF_FEM_2BK", "Female Clothing", 100, "" },
    			{ "U_C_Uniform_Farmer_01_F", "", 1000, "" },
    			{ "U_I_L_Uniform_01_tshirt_black_F", "PsiSyn Shirt", 1000, "" },
    			{ "U_I_L_Uniform_01_tshirt_olive_F", "", 1000, "" },
    			{ "U_I_L_Uniform_01_tshirt_skull_F", "", 1000, "" },
    			{ "U_I_L_Uniform_01_tshirt_sport_F", "", 1000, "" },
    			{ "U_C_Uniform_Scientist_01_formal_F", "", 2500, "" },
    			{ "U_C_Uniform_Scientist_01_F", "", 1000, "" },
    			{ "U_C_Uniform_Scientist_02_F", "", 1000, "" },
    			{ "U_C_Uniform_Scientist_02_formal_F", "", 1000, "" },
    			{ "U_O_R_Gorka_01_black_F", "", 5000, "" },
    			{ "U_C_E_LooterJacket_01_F", "", 1000, "" },
		        { "TRYK_U_B_PCUODs", "", 20, "call life_copdept in [5,7]" },
		        { "TRYK_U_B_PCUGs_gry", "", 20, "call life_copdept in [5,7]" },
		        { "TRYK_U_B_GRY_PCUs", "", 20, "call life_copdept in [5,7]" },
		        { "TRYK_U_B_PCUGs_BLK", "", 20, "call life_copdept in [5,7]" },
		        { "TRYK_U_B_PCUGs_OD_R", "", 20, "call life_copdept in [5,7]" },
		        { "TRYK_U_B_PCUODHs", "", 20, "call life_copdept in [5,7]" },
		        { "TRYK_U_B_PCUHs", "", 20, "call life_copdept in [5,7]" },
		        { "TRYK_U_B_PCUGHs", "", 20, "call life_copdept in [5,7]" },
		        { "TRYK_U_Bts_PCUs", "", 20, "call life_copdept in [5,7]" }
        };

        headgear[] = {
          { "NONE", $STR_C_Remove_headgear, 0, "" },
			    { "JD_bikerhat", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2000" },
				{ "H_SpidermanMask", "新手镇帽子", 500, "group player getVariable ['gang_id',-1] isEqualTo 332" },
			    { "H_RacingHelmet_1_black_F", "", 100, "" },
			    { "H_RacingHelmet_1_red_F", "", 100, "" },
			    { "H_RacingHelmet_1_white_F", "", 100, "" },
			    { "H_RacingHelmet_1_blue_F", "", 100, "" },
			    { "H_RacingHelmet_1_yellow_F", "", 100, "" },
			    { "H_RacingHelmet_1_green_F", "", 100, "" },
			    { "H_RacingHelmet_1_F", "", 200, "" },
			    { "H_RacingHelmet_2_F", "", 200, "" },
			    { "H_RacingHelmet_3_F", "", 200, "" },
			    { "H_RacingHelmet_4_F", "", 200, "" },
			    {"anzus_CAP_christmas_head_a", "", 30, ""},
			    {"anzus_CAP_christmas_head_b", "", 30, ""},
			    {"anzus_CAP_christmas_head_c", "", 30, ""},
			    {"anzus_CAP_christmas_head_d", "", 30, ""},
			    {"anzus_CAP_christmas_head_e", "", 30, ""},
			    {"anzus_CAP_christmas_head_f", "", 30, ""},
			    {"anzus_CAP_christmas_head_g", "", 30, ""},
			    {"anzus_CAP_christmas_head_h", "", 30, ""},
			    {"anzus_CAP_christmas_head1", "", 30, ""},
			    {"anzus_CAP_christmas_head2_a", "", 30, ""},
			    {"anzus_CAP_christmas_head2_b", "", 30, ""},
			    {"anzus_CAP_christmas_head2_c", "", 30, ""},
			    {"anzus_CAP_christmas_head2_d", "", 30, ""},
			    {"anzus_CAP_christmas_head3_a", "", 30, ""},
			    {"anzus_CAP_christmas_head3_b", "", 30, ""},
			    {"anzus_CAP_christmas_head3_c", "", 30, ""},
			    {"anzus_CAP_christmas_head3_d", "", 30, ""},
			    {"anzus_CAP_christmas_head4_a", "", 30, ""},
			    {"anzus_CAP_christmas_head4_b", "", 30, ""},
			    {"anzus_CAP_christmas_head4_c", "", 30, ""},
			    {"anzus_CAP_christmas_head4_d", "", 30, ""},
			    {"anzus_CAP_christmas_head4_e", "", 30, ""},
			    {"anzus_CAP_christmas_head4_f", "", 30, ""},
			    {"anzus_CAP_christmas_head4_g", "", 30, ""},
			    {"anzus_CAP_christmas_head4_h", "", 30, ""},
			    {"anzus_CAP_christmas_head5_a", "", 30, ""},
			    {"anzus_CAP_christmas_head5_b", "", 30, ""},
			    {"anzus_CAP_christmas_head5_c", "", 30, ""},
			    {"anzus_CAP_christmas_head5_d", "", 30, ""},
			    {"anzus_CAP_christmas_head5_e", "", 30, ""},
			    {"anzus_CAP_christmas_head5_f", "", 30, ""},
			    {"anzus_CAP_christmas_head5_g", "", 30, ""},
			    {"anzus_CAP_christmas_head5_h", "", 30, ""},
			    {"anzus_CAP_p_head_000_a", "", 30, ""},
			    {"anzus_CAP_p_head_000_b", "", 30, ""},
			    {"anzus_CAP_p_head_000_c", "", 30, ""},
			    {"anzus_CAP_p_head_000_d", "", 30, ""},
			    {"anzus_CAP_p_head_000_e", "", 30, ""},
			    {"anzus_CAP_p_head_000_f", "", 30, ""},
			    {"anzus_CAP_p_head_000_g", "", 30, ""},
			    {"anzus_CAP_p_head_000_h", "", 30, ""},
			    {"anzus_CAP_p_head_000_i", "", 30, ""},
			    {"anzus_CAP_p_head_000_j", "", 30, ""},
			    {"anzus_CAP_p_head_000_k", "", 30, ""},
			    {"anzus_CAP_p_head_000_l", "", 30, ""},
			    {"anzus_CAP_p_head_000_m", "", 30, ""},
			    {"anzus_CAP_p_head_000_n", "", 30, ""},
			    {"anzus_CAP_p_head_000_o", "", 30, ""},
			    {"anzus_CAP_p_head_000_p", "", 30, ""},
			    {"anzus_CAP_p_head_000_q", "", 30, ""},
			    {"anzus_CAP_p_head_000_r", "", 30, ""},
			    {"anzus_CAP_p_head_000_s", "", 30, ""},
			    {"anzus_CAP_p_head_000_t", "", 30, ""},
			    {"anzus_CAP_p_head_001_a", "", 30, ""},
			    {"anzus_CAP_p_head_001_b", "", 30, ""},
			    {"anzus_CAP_p_head_001_c", "", 30, ""},
			    {"anzus_CAP_p_head_001_d", "", 30, ""},
			    {"anzus_CAP_p_head_001_e", "", 30, ""},
			    {"anzus_CAP_p_head_001_f", "", 30, ""},
			    {"anzus_CAP_p_head_001_g", "", 30, ""},
			    {"anzus_CAP_p_head_001_h", "", 30, ""},
			    {"anzus_CAP_p_head_001_i", "", 30, ""},
			    {"anzus_CAP_p_head_001_j", "", 30, ""},
			    {"anzus_CAP_p_head_004_a", "", 30, ""},
			    {"anzus_CAP_p_head_004_b", "", 30, ""},
			    {"anzus_CAP_p_head_004_c", "", 30, ""},
			    {"anzus_CAP_p_head_004_d", "", 30, ""},
			    {"anzus_CAP_p_head_004_e", "", 30, ""},
			    {"anzus_CAP_p_head_004_f", "", 30, ""},
			    {"anzus_CAP_p_head_004_g", "", 30, ""},
			    {"anzus_CAP_p_head_004_h", "", 30, ""},
			    {"anzus_CAP_p_head_004_i", "", 30, ""},
			    {"anzus_CAP_p_head_004_j", "", 30, ""},
			    {"anzus_CAP_p_head_004_k", "", 30, ""},
			    {"anzus_CAP_p_head_004_l", "", 30, ""},
			    {"anzus_CAP_p_head_004_m", "", 30, ""},
			    {"anzus_CAP_p_head_005_a", "", 30, ""},
			    {"anzus_CAP_p_head_005_b", "", 30, ""},
			    {"anzus_CAP_p_head_005_c", "", 30, ""},
			    {"anzus_CAP_p_head_005_d", "", 30, ""},
			    {"anzus_CAP_p_head_005_e", "", 30, ""},
			    {"anzus_CAP_p_head_005_f", "", 30, ""},
			    {"anzus_CAP_p_head_005_g", "", 30, ""},
			    {"anzus_CAP_p_head_005_h", "", 30, ""},
			    {"anzus_CAP_p_head_005_i", "", 30, ""},
			    {"anzus_CAP_p_head_005_j", "", 30, ""},
			    {"anzus_CAP_p_head_005_k", "", 30, ""},
			    {"anzus_CAP_p_head_005_l", "", 30, ""},
			    {"anzus_CAP_p_head_005_m", "", 30, ""},
			    {"anzus_CAP_p_head_005_n", "", 30, ""},
			    {"anzus_CAP_p_head_005_o", "", 30, ""},
			    {"anzus_CAP_p_head_005_p", "", 30, ""},
			    {"anzus_CAP_p_head_005_q", "", 30, ""},
			    {"anzus_CAP_p_head_005_r", "", 30, ""},
			    {"anzus_CAP_p_head_005_s", "", 30, ""},
			    {"anzus_CAP_p_head_005_t", "", 30, ""},
			    {"anzus_CAP_p_head_005_u", "", 30, ""},
			    {"anzus_CAP_p_head_005_v", "", 30, ""},
			    {"anzus_CAP_p_head_005_w", "", 30, ""},
			    {"anzus_CAP_p_head_005_x", "", 30, ""},
			    {"anzus_CAP_p_head_005_y", "", 30, ""},
			    {"anzus_CAP_p_head_005_z", "", 30, ""},
			    {"anzus_CAP_p_head_006_a", "", 30, ""},
			    {"anzus_CAP_p_head_006_b", "", 30, ""},
			    {"anzus_CAP_berd_000_u_a", "", 30, ""},
			    {"anzus_CAP_berd_000_u_b", "", 30, ""},
			    {"anzus_CAP_berd_000_u_c", "", 30, ""},
			    {"anzus_CAP_berd_000_u_d", "", 30, ""},
			    {"anzus_CAP_berd_000_u_e", "", 30, ""},
			    {"anzus_CAP_berd_002_u_a", "", 30, ""},
			    {"anzus_CAP_berd_002_u_b", "", 30, ""},
			    {"anzus_CAP_berd_002_u_c", "", 30, ""},
			    {"anzus_CAP_berd_002_u_d", "", 30, ""},
			    {"anzus_CAP_berd_002_u_e", "", 30, ""},
			    {"anzus_CAP_berd_002_u_f", "", 30, ""},
			    {"anzus_CAP_berd_002_u_g", "", 30, ""},
			    {"anzus_CAP_berd_002_u_h", "", 30, ""},
			    {"anzus_CAP_berd_002_u_i", "", 30, ""},
			    {"anzus_CAP_berd_002_u_j", "", 30, ""},
			    {"anzus_CAP_berd_002_u_k", "", 30, ""},
			    {"anzus_CAP_berd_002_u_l", "", 30, ""},
			    {"anzus_CAP_berd_002_u_m", "", 30, ""},
			    {"anzus_CAP_berd_002_u_n", "", 30, ""},
			    {"anzus_CAP_berd_002_u_o", "", 30, ""},
			    {"anzus_CAP_berd_002_u_p", "", 30, ""},
			    {"anzus_CAP_berd_002_u_q", "", 30, ""},
			    {"anzus_CAP_berd_002_u_r", "", 30, ""},
			    {"anzus_CAP_berd_002_u_s", "", 30, ""},
			    {"anzus_CAP_berd_002_u_t", "", 30, ""},
			    {"anzus_CAP_berd_002_u_u", "", 30, ""},
			    {"anzus_CAP_berd_002_u_v", "", 30, ""},
			    {"anzus_CAP_berd_002_u_w", "", 30, ""},
			    {"anzus_CAP_berd_002_u_x", "", 30, ""},
			    {"anzus_CAP_berd_002_u_y", "", 30, ""},
			    {"anzus_CAP_berd_002_u_z", "", 30, ""},
			    {"anzus_CAP_berd_003_u_a", "", 30, ""},
			    {"anzus_CAP_berd_003_u_b", "", 30, ""},
			    {"anzus_CAP_berd_003_u_c", "", 30, ""},
			    {"anzus_CAP_berd_003_u_d", "", 30, ""},
			    {"anzus_CAP_berd_003_u_e", "", 30, ""},
			    {"anzus_CAP_berd_003_u_f", "", 30, ""},
			    {"anzus_CAP_berd_003_u_g", "", 30, ""},
			    {"anzus_CAP_berd_003_u_h", "", 30, ""},
			    {"anzus_CAP_berd_003_u_i", "", 30, ""},
			    {"anzus_CAP_berd_003_u_j", "", 30, ""},
			    {"anzus_CAP_berd_003_u_k", "", 30, ""},
			    {"anzus_CAP_berd_003_u_l", "", 30, ""},
			    {"anzus_CAP_berd_003_u_m", "", 30, ""},
			    {"anzus_CAP_berd_003_u_n", "", 30, ""},
			    {"anzus_CAP_berd_003_u_o", "", 30, ""},
			    {"anzus_CAP_berd_003_u_p", "", 30, ""},
			    {"anzus_CAP_berd_003_u_q", "", 30, ""},
			    {"anzus_CAP_berd_003_u_r", "", 30, ""},
			    {"anzus_CAP_berd_003_u_s", "", 30, ""},
			    {"anzus_CAP_berd_003_u_t", "", 30, ""},
			    {"anzus_CAP_berd_003_u_u", "", 30, ""},
			    {"anzus_CAP_berd_003_u_v", "", 30, ""},
			    {"anzus_CAP_berd_003_u_w", "", 30, ""},
			    {"anzus_CAP_berd_003_u_x", "", 30, ""},
			    {"anzus_CAP_berd_003_u_y", "", 30, ""},
			    {"anzus_CAP_berd_003_u_z", "", 30, ""},
			    {"anzus_CAP_berd_004_u_a", "", 30, ""},
			    {"anzus_CAP_berd_004_u_b", "", 30, ""},
			    {"anzus_CAP_berd_004_u_c", "", 30, ""},
			    {"anzus_CAP_berd_004_u_d", "", 30, ""},
			    {"anzus_CAP_berd_004_u_e", "", 30, ""},
			    {"anzus_CAP_berd_004_u_f", "", 30, ""},
			    {"anzus_CAP_berd_004_u_g", "", 30, ""},
			    {"anzus_CAP_berd_004_u_i", "", 30, ""},
			    {"anzus_CAP_berd_004_u_k", "", 30, ""},
			    {"anzus_CAP_berd_004_u_n", "", 30, ""},
			    {"anzus_CAP_berd_004_u_s", "", 30, ""},
			    {"anzus_CAP_berd_004_u_j", "", 30, ""},
			    {"anzus_CAP_berd_006_u_a", "", 30, ""},
			    {"anzus_CAP_berd_006_u_b", "", 30, ""},
			    {"anzus_CAP_berd_006_u_c", "", 30, ""},
			    {"anzus_CAP_berd_006_u_d", "", 30, ""},
			    {"anzus_CAP_berd_006_u_e", "", 30, ""},
			    {"anzus_CAP_berd_006_u_f", "", 30, ""},
			    {"anzus_CAP_berd_006_u_g", "", 30, ""},
			    {"anzus_CAP_berd_006_u_h", "", 30, ""},
			    {"anzus_CAP_berd_006_u_i", "", 30, ""},
			    {"anzus_CAP_berd_006_u_j", "", 30, ""},
			    {"anzus_CAP_berd_006_u_k", "", 30, ""},
			    {"anzus_CAP_berd_006_u_l", "", 30, ""},
			    {"anzus_CAP_berd_006_u_m", "", 30, ""},
			    {"anzus_CAP_berd_006_u_n", "", 30, ""},
			    {"anzus_CAP_berd_011_u_a", "", 30, ""},
			    {"anzus_CAP_berd_011_u_b", "", 30, ""},
			    {"anzus_CAP_berd_011_u_c", "", 30, ""},
			    {"anzus_CAP_berd_011_u_d", "", 30, ""},
			    {"anzus_CAP_berd_011_u_e", "", 30, ""},
			    {"anzus_CAP_berd_011_u_f", "", 30, ""},
			    {"anzus_CAP_berd_011_u_g", "", 30, ""},
			    {"anzus_CAP_berd_011_u_h", "", 30, ""},
			    {"anzus_CAP_berd_011_u_i", "", 30, ""},
			    {"anzus_CAP_berd_011_u_j", "", 30, ""},
			    {"anzus_CAP_berd_011_u_k", "", 30, ""},
			    {"anzus_CAP_berd_011_u_l", "", 30, ""},
			    {"anzus_CAP_berd_011_u_m", "", 30, ""},
			    {"anzus_CAP_berd_011_u_n", "", 30, ""},
			    {"anzus_CAP_berd_011_u_o", "", 30, ""},
			    {"anzus_CAP_berd_011_u_p", "", 30, ""},
			    {"anzus_CAP_berd_011_u_q", "", 30, ""},
			    {"anzus_CAP_berd_011_u_r", "", 30, ""},
			    {"anzus_CAP_berd_011_u_s", "", 30, ""},
			    {"anzus_CAP_berd_011_u_t", "", 30, ""},
			    {"anzus_CAP_berd_011_u_u", "", 30, ""},
			    {"anzus_CAP_berd_011_u_v", "", 30, ""},
			    {"anzus_CAP_berd_011_u_w", "", 30, ""},
			    {"anzus_CAP_berd_011_u_x", "", 30, ""},
			    {"anzus_CAP_char_sniper", "", 30, ""},
			    {"anzus_CAP_beanie", "", 30, ""},
			    {"anzus_CAP_beanie1", "", 30, ""},
			    {"anzus_CAP_beanie2", "", 30, ""},
			    {"anzus_CAP_beanie3", "", 30, ""},
			    {"anzus_CAP_beanie4", "", 30, ""},
			    {"anzus_CAP_beanie5", "", 30, ""},
			    {"anzus_CAP_beanie6", "", 30, ""},
			    {"anzus_CAP_beanie7", "", 30, ""},
			    {"anzus_CAP_beanie8", "", 30, ""},
			    {"anzus_CAP_beanie_1", "", 30, ""},
			    {"anzus_CAP_beanie_1_a", "", 30, ""},
			    {"anzus_CAP_beanie_1_b", "", 30, ""},
			    {"anzus_CAP_beanie_1_c", "", 30, ""},
			    {"anzus_CAP_beanie_1_d", "", 30, ""},
			    {"anzus_CAP_beanie_1_e", "", 30, ""},
			    {"anzus_CAP_beanie_1_f", "", 30, ""},
			    {"anzus_CAP_beanie_1_g", "", 30, ""},
			    {"anzus_CAP_beanie_1_h", "", 30, ""},
			    {"anzus_CAP_beanie_1_i", "", 30, ""},
			    {"anzus_CAP_beanie_1_j", "", 30, ""},
			    {"anzus_CAP_beanie_1_k", "", 30, ""},
			    {"anzus_CAP_beanie_1_l", "", 30, ""},
			    {"anzus_CAP_beanie_1_m", "", 30, ""},
			    {"anzus_CAP_beanie_2_a", "", 30, ""},
			    {"anzus_CAP_beanie_2_b", "", 30, ""},
			    {"anzus_CAP_beanie_2_c", "", 30, ""},
			    {"anzus_CAP_beanie_2_d", "", 30, ""},
			    {"anzus_CAP_beanie_2_e", "", 30, ""},
			    {"anzus_CAP_beanie_2_f", "", 30, ""},
			    {"anzus_CAP_beanie_2_g", "", 30, ""},
			    {"anzus_CAP_beanie_2_h", "", 30, ""},
			    {"anzus_CAP_beanie_2_i", "", 30, ""},
			    {"anzus_CAP_beanie_2_j", "", 30, ""},
			    {"anzus_CAP_beanie_2_k", "", 30, ""},
			    {"anzus_CAP_beanie_2_l", "", 30, ""},
			    {"anzus_CAP_beanie_2_m", "", 30, ""},
			    {"anzus_CAP_beanie_2_n", "", 30, ""},
			    {"anzus_CAP_beanie_2_o", "", 30, ""},
			    {"anzus_CAP_Embacy", "", 30, ""},
			    {"anzus_CAP_furcap", "", 30, ""},
			    {"anzus_CAP_russelite_hat", "", 30, ""},
			    {"anzus_CAP_Headgear", "", 30, ""},
			    {"anzus_CAP_Headgear1", "", 30, ""},
			    {"anzus_CAP_Headgear_1", "", 30, ""},
			    {"anzus_CAP_Headgear1_1", "", 30, ""}
        };

        goggles[] = {
			    { "NONE", $STR_C_Remove_goggles, 0, "" },
			    { "V12_CIGAR2", "法官专属制服", 50, "getPlayerUID player in ['76561199063859158','76561199014404395','76561198978158050']" },
				{ "JD_Pipe", "法官专属制服", 50, "getPlayerUID player in ['76561199063859158','76561199014404395','76561198978158050']" },
				{ "G_Shades_Black", "", 20, "" },
			    { "G_Shades_Blue", "", 20, "" },
			    { "G_Shades_Green", "", 20, "" },
			    { "G_Shades_Red", "", 20, "" },
			    { "G_Sport_Blackred", "", 25, "" },
			    { "G_Sport_BlackWhite", "", 25, "" },
			    { "G_Sport_Blackyellow", "", 25, "" },
			    { "G_Sport_Checkered", "", 25, "" },
			    { "G_Sport_Greenblack", "", 25, "" },
			    { "G_Sport_Red", "", 25, "" },
			    { "G_Lowprofile", "", 20, "" },
			    { "G_Squares", "", 20, "" },
			    { "G_Aviator", "", 50, "" },
			    { "G_Combat", "", 23, "" },
			    { "G_Lady_Mirror", "", 26, "" },
			    { "G_Lady_Dark", "", 26, "" },
			    { "G_Lady_Blue", "", 26, "" },
			    { "anzus_p_eyes_000_a", "", 50, "" },
			    { "anzus_p_eyes_000_b", "", 50, "" },
			    { "anzus_p_eyes_000_c", "", 50, "" },
			    { "anzus_p_eyes_000_d", "", 50, "" },
			    { "anzus_p_eyes_000_e", "", 50, "" },
			    { "anzus_p_eyes_000_f", "", 50, "" },
			    { "anzus_p_eyes_000_g", "", 50, "" },
			    { "anzus_p_eyes_000_h", "", 50, "" },
			    { "anzus_p_eyes_000_i", "", 50, "" },
			    { "anzus_p_eyes_000_j", "", 50, "" },
			    { "anzus_p_eyes_000_k", "", 50, "" },
			    { "anzus_p_eyes_000_l", "", 50, "" },
			    { "anzus_p_eyes_000_m", "", 50, "" },
			    { "anzus_p_eyes_000_n", "", 50, "" },
			    { "anzus_p_eyes_000_o", "", 50, "" },
			    { "anzus_p_eyes_001", "", 50, "" },
			    { "anzus_Glasses_scarf_a", "", 50, "" },
			    { "anzus_Glasses_scarf_b", "", 50, "" },
			    { "anzus_Glasses_scarf_c", "", 50, "" },
			    { "anzus_Glasses_scarf1_a", "", 50, "" },
			    { "anzus_Glasses_scarf1_b", "", 50, "" },
			    { "anzus_Glasses_scarf1_c", "", 50, "" },
			    { "anzus_Glasses_scarf1_d", "", 50, "" },
			    { "anzus_Glasses_scarf2_a", "", 50, "" },
			    { "anzus_Glasses_scarf2_b", "", 50, "" },
			    { "anzus_Glasses_scarf2_c", "", 50, "" },
			    { "anzus_Glasses_scarf2_d", "", 50, "" },
			    { "anzus_Glasses_scarf2_e", "", 50, "" },
			    { "anzus_Glasses_scarf2_f", "", 50, "" }
        };
        vests[] = {
			    { "NONE", $STR_C_Remove_vests, 0, "" },
			    { "JD_BikerVest10", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2000" },
			    { "V_Safety_blue_F", "Saftey Blue", 50, "" },
			    { "V_Safety_orange_F", "Saftey Orange", 50, "" },
			    { "V_Safety_yellow_F", "Saftey Yellow", 50, "" },
				{ "AG_SchneiderVest", "新手镇背心", 500, "group player getVariable ['gang_id',-1] isEqualTo 332" },
			    { "anzus_vest_1", "", 450, "" },
			    { "anzus_vest_1_a", "", 450, "" },
			    { "anzus_vest_1_b", "", 450, "" },
			    { "anzus_vest_1_c", "", 450, "" },
			    { "anzus_vest_1_d", "", 450, "" },
			    { "anzus_vest_1_e", "", 450, "" },
			    { "anzus_vest_1_f", "", 450, "" },
			    { "anzus_vest_1_g", "", 450, "" },
			    { "anzus_vest_1_h", "", 450, "" },
			    { "anzus_vest_1_i", "", 450, "" },
			    { "anzus_vest_1_j", "", 450, "" },
			    { "anzus_vest_1_k", "", 450, "" },
			    { "anzus_vest_1_l", "", 450, "" },
			    { "anzus_vest_1_m", "", 450, "" },
			    { "anzus_vest_1_n", "", 450, "" },
			    { "anzus_vest_1_o", "", 450, "" },
			    { "anzus_vest_1_p", "", 450, "" },
			    { "anzus_vest_1_q", "", 450, "" },
			    { "anzus_vest_1_r", "", 450, "" },
			    { "anzus_vest_1_s", "", 450, "" },
			    { "anzus_vest_1_t", "", 450, "" },
			    { "anzus_vest_1_u", "", 450, "" },
			    { "anzus_vest_1_v", "", 450, "" },
			    { "anzus_vest_1_w", "", 450, "" },
			    { "anzus_vest_1_x", "", 450, "" },
			    { "anzus_vest_1_y", "", 450, "" },
			    { "anzus_vest_1_z", "", 450, "" }
        };
        backpacks[] = {
			    { "NONE", $STR_C_Remove_backpacks, 0, "" },
			    { "B_OutdoorPack_blk", "", 150, "" },
			    { "B_AssaultPack_khk", "", 200, "" },
			    { "B_AssaultPack_dgtl", "", 200, "" },
			    { "B_AssaultPack_rgr", "", 200, "" },
			    { "B_AssaultPack_sgg", "", 200, "" },
			    { "B_AssaultPack_blk", "", 200, "" },
			    { "B_AssaultPack_cbr", "", 200, "" },
			    { "B_AssaultPack_mcamo", "", 200, "" },
			    { "B_AssaultPack_tna_f", "", 200, "" },
			    { "B_TacticalPack_oli", "", 200, "" },
			    { "B_Kitbag_mcamo", "", 300, "" },
			    { "B_Kitbag_sgg", "", 300, "" },
			    { "B_Kitbag_cbr", "", 300, "" },
			    { "B_FieldPack_blk", "", 400, "" },
			    { "B_FieldPack_ocamo", "", 400, "" },
			    { "B_FieldPack_oucamo", "", 400, "" },
			    { "B_FieldPack_ghex_f", "", 400, "" },
			    { "B_Bergen_sgg", "", 500, "" },
			    { "B_Bergen_mcamo", "", 500, "" },
			    { "B_Bergen_rgr", "", 500, "" },
			    { "B_Bergen_blk", "", 500, "" },
			    { "B_Carryall_ocamo", "", 550, "" },
			    { "B_Carryall_oucamo", "", 550, "" },
			    { "B_Carryall_mcamo", "", 550, "" },
			    { "B_Carryall_oli", "", 550, "" },
			    { "B_Carryall_khk", "", 550, "" },
			    { "B_Carryall_cbr", "", 550, "" },
			    { "B_Carryall_ghex_f", "", 650, "" },
			    { "B_Bergen_dgtl_f", "", 650, "" },
			    { "B_AssaultPack_mcamo", "", 200, "" },
			    { "B_TacticalPack_oli", "", 30, "" },
			    { "B_Kitbag_mcamo", "", 300, "" },
			    { "B_Kitbag_sgg", "", 300, "" },
			    { "B_Kitbag_cbr", "", 300, "" },
			    { "B_FieldPack_blk", "", 500, "" },
			    { "B_FieldPack_ocamo", "", 500, "" },
			    { "B_FieldPack_oucamo", "", 500, "" },
			    { "B_Bergen_sgg", "", 650, "" },
			    { "B_Bergen_mcamo", "", 650, "" },
			    { "B_Bergen_rgr", "", 650, "" },
			    { "B_Bergen_blk", "", 650, "" },
			    { "B_Carryall_ocamo", "", 750, "" },
			    { "B_Carryall_oucamo", "", 750, "" },
			    { "B_Carryall_mcamo", "", 750, "" },
			    { "B_Carryall_oli", "", 750, "" },
			    { "B_Carryall_khk", "", 750, "" },
			    { "B_Carryall_cbr", "", 750, "" },
			    { "anzus_backpack", "", 800, "" },
			    { "anzus_backpack_a", "", 800, "" },
			    { "anzus_backpack_b", "", 800, "" },
			    { "anzus_backpack_c", "", 800, "" },
			    { "anzus_backpack_d", "", 800, "" },
			    { "anzus_backpack_e", "", 800, "" },
			    { "anzus_backpack_f", "", 800, "" },
			    { "anzus_backpack_g", "", 800, "" },
			    { "anzus_backpack_h", "", 800, "" },
			    { "anzus_backpack_i", "", 800, "" },
			    { "anzus_backpack_j", "", 800, "" },
			    { "anzus_backpack_k", "", 800, "" },
			    { "anzus_backpack_l", "", 800, "" },
			    { "anzus_backpack_m", "", 800, "" }
        };
    };

    class rebel {
        title = "STR_Shops_C_Rebel";
        conditions = "";
        side = "";
        uniforms[] = {
			    { "NONE", $STR_C_Remove_uniforms, 0, "" },
				{ "AG_AsylumUniform", "廉政公署", 5000, "group player getVariable ['gang_id',-1] isEqualTo 320" },
				{ "AG_YakuzaUniform", "七点专属定制服装", 500, "getPlayerUID player in ['76561199014404395']" },
			    { "AG_ChauUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 1001" }, // corvo
			    { "AG_ShadowDivUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 1002" }, //shadowdiv
			    { "AG_MillersUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 1003" }, // free family
			    { "AG_CliqueUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2025" }, // clique
			    { "AG_UrFatUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 1008" }, // ur fat
			    { "vvv_traje_ejecutivo_1", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2028" }, // hope
			    { "AG_UCUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2030" }, // umbrella
			    { "AG_atlasUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2008" }, // nice patrol
			    { "AG_SpetsUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 1025" }, //spets
      		{ "AG_LucasUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2048" }, //lucas
      		{ "AG_ffUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2005" },	//brigade nord
      		{ "AG_NMAUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2031" },
      		{ "AG_BPUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2000" },
      		{ "AG_SCUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 1013" },
      		{ "AG_PMCUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2073" },
      		{ "AG_WPUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2039" },
			{ "AG_UOUniform", "代号007定制服装", 500, "group player getVariable ['gang_id',-1] isEqualTo 329" },
  				{ "AG_ManarelloUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2087" },
  				{ "vvv_traje_robot_1", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2086" },
  				{ "AG_MT6Uniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2077" },
  				{ "AG_YakuzaUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2011" },
  				{ "AG_OTUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2092" },
  				{ "AG_TillerUniform", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2088" },
  				{ "AG_OutlawUniform", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2150" },
  				{ "AG_GMUniform_Soldier", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2123" },
  				{ "AG_DelgadoUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2095" }, // corvo
  				{ "AG_RussianPlayboyUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2043" },
  				{ "AG_PsiUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2129" },
  				{ "AG_MongrelUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 3001" },
  				{ "AG_DiamondUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 3042" },
  				{ "AG_CaponeUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2153" },
				{ "AG_DHUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 3002" },
				{ "AG_MDCUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2026" },	
				{ "AG_NostraUniform", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 3028" },	
				
      		{ "U_I_C_Soldier_Bandit_4_F", "", 250, ""},
      		{ "TRYK_U_B_PCUODs", "", 250, ""},
      		{ "TRYK_U_B_PCUGs_gry", "", 250, ""},
      		{ "TRYK_U_B_GRY_PCUs", "", 250, ""},
      		{ "TRYK_U_B_PCUGs_BLK", "", 250, ""},
      		{ "TRYK_U_B_PCUGs_OD_R", "", 250, ""},
      		{ "TRYK_U_B_PCUODHs", "", 250, ""},
      		{ "TRYK_U_B_PCUHs", "", 250, ""},
      		{ "TRYK_U_B_PCUGHs", "", 250, ""},
      		{ "TRYK_U_Bts_PCUs", "", 250, ""},
      		{ "TRYK_U_B_MTP_BLK_CombatUniform", "", 250, ""},
      		{ "TRYK_U_B_BLK_OD", "", 250, ""},
      		{ "TRYK_U_B_C01_Tsirt", "", 250, ""},
      		{ "TRYK_U_B_BLKTAN_CombatUniform", "", 250, ""},
      		{ "TRYK_U_B_AOR2_BLK_R_CombatUniform", "", 250, ""},
      		{ "TRYK_U_B_WOOD_MARPAT_CombatUniform", "", 250, ""},
      		{ "TRYK_U_B_Wood_T", "", 250, ""},
      		{ "TRYK_ZARATAKI", "", 250, ""},
      		{ "TRYK_ZARATAKI2", "", 250, ""},
      		{ "TRYK_ZARATAKI3", "", 250, ""},
      		{ "TRYK_T_CSAT_PAD", "", 250, ""},
      		{ "U_B_survivAG_uniform", "", 250, ""},
      		{ "U_B_CombatUniform_Sigma", "", 250, ""},
      		{ "U_I_C_Soldier_Para_1_F", "", 250, ""},
      		{ "U_I_C_Soldier_Para_4_F", "", 250, ""},
      		{ "U_I_C_Soldier_Para_5_F", "", 250, ""},
      		{ "U_I_C_Soldier_Para_3_F", "", 250, ""},
      		{ "U_I_C_Soldier_Para_2_F", "", 250, ""},
      		{ "U_BG_Guerilla1_2_F", "", 250, ""},
      		{ "PAT_nigga", "", 500, ""},
      		{ "PAT_nigga2_1", "", 500, ""},
      		{ "PAT_nigga3", "", 500, ""},
      		{ "PAT_nigga2_3", "", 500, ""},
      		{ "PAT_nigga6", "", 500, ""},
      		{ "PAT_nigga2_6", "", 500, ""},
      		{ "PAT_nigga2", "", 500, ""},
      		{ "PAT_nigga2_2", "", 500, ""},
      		{ "PAT_nigga4", "", 500, ""},
      		{ "PAT_nigga2_4", "", 500, ""},
      		{ "PAT_nigga5", "", 500, ""},
      		{ "PAT_nigga2_5", "", 500, ""},
      		{ "AG_GangU_Frank", "", 1000, ""},
      		{ "AG_GangU_RPD", "", 1000, ""}
        };

        headgear[] = {
			    { "NONE", $STR_C_Remove_headgear, 0, "" },
				{ "H_MickeyMask", "", 5000, "group player getVariable ['gang_id',-1] isEqualTo 320" },
				{ "anzus_CAP_p_head_001_d", "七点专属定制服装", 50, "getPlayerUID player in ['76561199014404395']" },
      		{"Shadow_Headgear", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 1002" },
      		{"V12_CROSS2", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2008" },
  				{"Playboy_Headgear", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2011" },
  				{"anzus_CAP_berd_000_u_a", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 3001" },
  				{"Delgado_Headgear", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2095" },
				{ "d3s_CAP_berd_002_u_b", "代号007定制服装", 50, "group player getVariable ['gang_id',-1] isEqualTo 329" },
				{"MDC_Headgear", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2026" },
				{"Devils_Headgear", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 3002" },
			    {"anzus_CAP_christmas_head_a", "", 30, ""},
			    {"anzus_CAP_christmas_head_b", "", 30, ""},
			    {"anzus_CAP_christmas_head_c", "", 30, ""},
			    {"anzus_CAP_christmas_head_d", "", 30, ""},
			    {"anzus_CAP_christmas_head_e", "", 30, ""},
			    {"anzus_CAP_christmas_head_f", "", 30, ""},
			    {"anzus_CAP_christmas_head_g", "", 30, ""},
			    {"anzus_CAP_christmas_head_h", "", 30, ""},
			    {"anzus_CAP_christmas_head1", "", 30, ""},
			    { "H_Cap_Oli", "", 30, "" },
          {"anzus_CAP_christmas_head2_a", "", 30, ""},
          {"anzus_CAP_christmas_head2_b", "", 30, ""},
          {"anzus_CAP_christmas_head2_c", "", 30, ""},
          {"anzus_CAP_christmas_head2_d", "", 30, ""},
          {"anzus_CAP_christmas_head3_a", "", 30, ""},
          {"anzus_CAP_christmas_head3_b", "", 30, ""},
          {"anzus_CAP_christmas_head3_c", "", 30, ""},
          {"anzus_CAP_christmas_head3_d", "", 30, ""},
          {"anzus_CAP_christmas_head4_a", "", 30, ""},
          {"anzus_CAP_christmas_head4_b", "", 30, ""},
          {"anzus_CAP_christmas_head4_c", "", 30, ""},
          {"anzus_CAP_christmas_head4_d", "", 30, ""},
          {"anzus_CAP_christmas_head4_e", "", 30, ""},
          {"anzus_CAP_christmas_head4_f", "", 30, ""},
          {"anzus_CAP_christmas_head4_g", "", 30, ""},
          {"anzus_CAP_christmas_head4_h", "", 30, ""},
          {"anzus_CAP_christmas_head5_a", "", 30, ""},
          {"anzus_CAP_christmas_head5_b", "", 30, ""},
          {"anzus_CAP_christmas_head5_c", "", 30, ""},
          {"anzus_CAP_christmas_head5_d", "", 30, ""},
          {"anzus_CAP_christmas_head5_e", "", 30, ""},
          {"anzus_CAP_christmas_head5_f", "", 30, ""},
          {"anzus_CAP_christmas_head5_g", "", 30, ""},
          {"anzus_CAP_christmas_head5_h", "", 30, ""},
          {"anzus_CAP_p_head_000_a", "", 30, ""},
          {"anzus_CAP_p_head_000_b", "", 30, ""},
          {"anzus_CAP_p_head_000_c", "", 30, ""},
          {"anzus_CAP_p_head_000_d", "", 30, ""},
          {"anzus_CAP_p_head_000_e", "", 30, ""},
          {"anzus_CAP_p_head_000_f", "", 30, ""},
          {"anzus_CAP_p_head_000_g", "", 30, ""},
          {"anzus_CAP_p_head_000_h", "", 30, ""},
          {"anzus_CAP_p_head_000_i", "", 30, ""},
          {"anzus_CAP_p_head_000_j", "", 30, ""},
          {"anzus_CAP_p_head_000_k", "", 30, ""},
          {"anzus_CAP_p_head_000_l", "", 30, ""},
          {"anzus_CAP_p_head_000_m", "", 30, ""},
          {"anzus_CAP_p_head_000_n", "", 30, ""},
          {"anzus_CAP_p_head_000_o", "", 30, ""},
          {"anzus_CAP_p_head_000_p", "", 30, ""},
          {"anzus_CAP_p_head_000_q", "", 30, ""},
          {"anzus_CAP_p_head_000_r", "", 30, ""},
          {"anzus_CAP_p_head_000_s", "", 30, ""},
          {"anzus_CAP_p_head_000_t", "", 30, ""},
          {"anzus_CAP_p_head_001_a", "", 30, ""},
          {"anzus_CAP_p_head_001_b", "", 30, ""},
          {"anzus_CAP_p_head_001_c", "", 30, ""},
          {"anzus_CAP_p_head_001_d", "", 30, ""},
          {"anzus_CAP_p_head_001_e", "", 30, ""},
          {"anzus_CAP_p_head_001_f", "", 30, ""},
          {"anzus_CAP_p_head_001_g", "", 30, ""},
          {"anzus_CAP_p_head_001_h", "", 30, ""},
          {"anzus_CAP_p_head_001_i", "", 30, ""},
          {"anzus_CAP_p_head_001_j", "", 30, ""},
          {"anzus_CAP_p_head_004_a", "", 30, ""},
          {"anzus_CAP_p_head_004_b", "", 30, ""},
          {"anzus_CAP_p_head_004_c", "", 30, ""},
          {"anzus_CAP_p_head_004_d", "", 30, ""},
          {"anzus_CAP_p_head_004_e", "", 30, ""},
          {"anzus_CAP_p_head_004_f", "", 30, ""},
          {"anzus_CAP_p_head_004_g", "", 30, ""},
          {"anzus_CAP_p_head_004_h", "", 30, ""},
          {"anzus_CAP_p_head_004_i", "", 30, ""},
          {"anzus_CAP_p_head_004_j", "", 30, ""},
          {"anzus_CAP_p_head_004_k", "", 30, ""},
          {"anzus_CAP_p_head_004_l", "", 30, ""},
          {"anzus_CAP_p_head_004_m", "", 30, ""},
          {"anzus_CAP_p_head_005_a", "", 30, ""},
          {"anzus_CAP_p_head_005_b", "", 30, ""},
          {"anzus_CAP_p_head_005_c", "", 30, ""},
          {"anzus_CAP_p_head_005_d", "", 30, ""},
          {"anzus_CAP_p_head_005_e", "", 30, ""},
          {"anzus_CAP_p_head_005_f", "", 30, ""},
          {"anzus_CAP_p_head_005_g", "", 30, ""},
          {"anzus_CAP_p_head_005_h", "", 30, ""},
          {"anzus_CAP_p_head_005_i", "", 30, ""},
          {"anzus_CAP_p_head_005_j", "", 30, ""},
          {"anzus_CAP_p_head_005_k", "", 30, ""},
          {"anzus_CAP_p_head_005_l", "", 30, ""},
          {"anzus_CAP_p_head_005_m", "", 30, ""},
          {"anzus_CAP_p_head_005_n", "", 30, ""},
          {"anzus_CAP_p_head_005_o", "", 30, ""},
          {"anzus_CAP_p_head_005_p", "", 30, ""},
          {"anzus_CAP_p_head_005_q", "", 30, ""},
          {"anzus_CAP_p_head_005_r", "", 30, ""},
          {"anzus_CAP_p_head_005_s", "", 30, ""},
          {"anzus_CAP_p_head_005_t", "", 30, ""},
          {"anzus_CAP_p_head_005_u", "", 30, ""},
          {"anzus_CAP_p_head_005_v", "", 30, ""},
          {"anzus_CAP_p_head_005_w", "", 30, ""},
          {"anzus_CAP_p_head_005_x", "", 30, ""},
          {"anzus_CAP_p_head_005_y", "", 30, ""},
          {"anzus_CAP_p_head_005_z", "", 30, ""},
          {"anzus_CAP_p_head_006_a", "", 30, ""},
          {"anzus_CAP_p_head_006_b", "", 30, ""},
          {"anzus_CAP_berd_000_u_a", "", 30, ""},
          {"anzus_CAP_berd_000_u_b", "", 30, ""},
          {"anzus_CAP_berd_000_u_c", "", 30, ""},
          {"anzus_CAP_berd_000_u_d", "", 30, ""},
          {"anzus_CAP_berd_000_u_e", "", 30, ""},
          {"anzus_CAP_berd_002_u_a", "", 30, ""},
          {"anzus_CAP_berd_002_u_b", "", 30, ""},
          {"anzus_CAP_berd_002_u_c", "", 30, ""},
          {"anzus_CAP_berd_002_u_d", "", 30, ""},
          {"anzus_CAP_berd_002_u_e", "", 30, ""},
          {"anzus_CAP_berd_002_u_f", "", 30, ""},
          {"anzus_CAP_berd_002_u_g", "", 30, ""},
          {"anzus_CAP_berd_002_u_h", "", 30, ""},
          {"anzus_CAP_berd_002_u_i", "", 30, ""},
          {"anzus_CAP_berd_002_u_j", "", 30, ""},
          {"anzus_CAP_berd_002_u_k", "", 30, ""},
          {"anzus_CAP_berd_002_u_l", "", 30, ""},
          {"anzus_CAP_berd_002_u_m", "", 30, ""},
          {"anzus_CAP_berd_002_u_n", "", 30, ""},
          {"anzus_CAP_berd_002_u_o", "", 30, ""},
          {"anzus_CAP_berd_002_u_p", "", 30, ""},
          {"anzus_CAP_berd_002_u_q", "", 30, ""},
          {"anzus_CAP_berd_002_u_r", "", 30, ""},
          {"anzus_CAP_berd_002_u_s", "", 30, ""},
          {"anzus_CAP_berd_002_u_t", "", 30, ""},
          {"anzus_CAP_berd_002_u_u", "", 30, ""},
          {"anzus_CAP_berd_002_u_v", "", 30, ""},
          {"anzus_CAP_berd_002_u_w", "", 30, ""},
          {"anzus_CAP_berd_002_u_x", "", 30, ""},
          {"anzus_CAP_berd_002_u_y", "", 30, ""},
          {"anzus_CAP_berd_002_u_z", "", 30, ""},
          {"anzus_CAP_berd_003_u_a", "", 30, ""},
          {"anzus_CAP_berd_003_u_b", "", 30, ""},
          {"anzus_CAP_berd_003_u_c", "", 30, ""},
          {"anzus_CAP_berd_003_u_d", "", 30, ""},
          {"anzus_CAP_berd_003_u_e", "", 30, ""},
          {"anzus_CAP_berd_003_u_f", "", 30, ""},
          {"anzus_CAP_berd_003_u_g", "", 30, ""},
          {"anzus_CAP_berd_003_u_h", "", 30, ""},
          {"anzus_CAP_berd_003_u_i", "", 30, ""},
          {"anzus_CAP_berd_003_u_j", "", 30, ""},
          {"anzus_CAP_berd_003_u_k", "", 30, ""},
          {"anzus_CAP_berd_003_u_l", "", 30, ""},
          {"anzus_CAP_berd_003_u_m", "", 30, ""},
          {"anzus_CAP_berd_003_u_n", "", 30, ""},
          {"anzus_CAP_berd_003_u_o", "", 30, ""},
          {"anzus_CAP_berd_003_u_p", "", 30, ""},
          {"anzus_CAP_berd_003_u_q", "", 30, ""},
          {"anzus_CAP_berd_003_u_r", "", 30, ""},
          {"anzus_CAP_berd_003_u_s", "", 30, ""},
          {"anzus_CAP_berd_003_u_t", "", 30, ""},
          {"anzus_CAP_berd_003_u_u", "", 30, ""},
          {"anzus_CAP_berd_003_u_v", "", 30, ""},
          {"anzus_CAP_berd_003_u_w", "", 30, ""},
          {"anzus_CAP_berd_003_u_x", "", 30, ""},
          {"anzus_CAP_berd_003_u_y", "", 30, ""},
          {"anzus_CAP_berd_003_u_z", "", 30, ""},
          {"anzus_CAP_berd_004_u_a", "", 30, ""},
          {"anzus_CAP_berd_004_u_b", "", 30, ""},
          {"anzus_CAP_berd_004_u_c", "", 30, ""},
          {"anzus_CAP_berd_004_u_d", "", 30, ""},
          {"anzus_CAP_berd_004_u_e", "", 30, ""},
          {"anzus_CAP_berd_004_u_f", "", 30, ""},
          {"anzus_CAP_berd_004_u_g", "", 30, ""},
          {"anzus_CAP_berd_004_u_i", "", 30, ""},
          {"anzus_CAP_berd_004_u_k", "", 30, ""},
          {"anzus_CAP_berd_004_u_n", "", 30, ""},
          {"anzus_CAP_berd_004_u_s", "", 30, ""},
          {"anzus_CAP_berd_004_u_j", "", 30, ""},
          {"anzus_CAP_berd_006_u_a", "", 30, ""},
          {"anzus_CAP_berd_006_u_b", "", 30, ""},
          {"anzus_CAP_berd_006_u_c", "", 30, ""},
          {"anzus_CAP_berd_006_u_d", "", 30, ""},
          {"anzus_CAP_berd_006_u_e", "", 30, ""},
          {"anzus_CAP_berd_006_u_f", "", 30, ""},
          {"anzus_CAP_berd_006_u_g", "", 30, ""},
          {"anzus_CAP_berd_006_u_h", "", 30, ""},
          {"anzus_CAP_berd_006_u_i", "", 30, ""},
          {"anzus_CAP_berd_006_u_j", "", 30, ""},
          {"anzus_CAP_berd_006_u_k", "", 30, ""},
          {"anzus_CAP_berd_006_u_l", "", 30, ""},
          {"anzus_CAP_berd_006_u_m", "", 30, ""},
          {"anzus_CAP_berd_006_u_n", "", 30, ""},
          {"anzus_CAP_berd_011_u_a", "", 30, ""},
          {"anzus_CAP_berd_011_u_b", "", 30, ""},
          {"anzus_CAP_berd_011_u_c", "", 30, ""},
          {"anzus_CAP_berd_011_u_d", "", 30, ""},
          {"anzus_CAP_berd_011_u_e", "", 30, ""},
          {"anzus_CAP_berd_011_u_f", "", 30, ""},
          {"anzus_CAP_berd_011_u_g", "", 30, ""},
          {"anzus_CAP_berd_011_u_h", "", 30, ""},
          {"anzus_CAP_berd_011_u_i", "", 30, ""},
          {"anzus_CAP_berd_011_u_j", "", 30, ""},
          {"anzus_CAP_berd_011_u_k", "", 30, ""},
          {"anzus_CAP_berd_011_u_l", "", 30, ""},
          {"anzus_CAP_berd_011_u_m", "", 30, ""},
          {"anzus_CAP_berd_011_u_n", "", 30, ""},
          {"anzus_CAP_berd_011_u_o", "", 30, ""},
          {"anzus_CAP_berd_011_u_p", "", 30, ""},
          {"anzus_CAP_berd_011_u_q", "", 30, ""},
          {"anzus_CAP_berd_011_u_r", "", 30, ""},
          {"anzus_CAP_berd_011_u_s", "", 30, ""},
          {"anzus_CAP_berd_011_u_t", "", 30, ""},
          {"anzus_CAP_berd_011_u_u", "", 30, ""},
          {"anzus_CAP_berd_011_u_v", "", 30, ""},
          {"anzus_CAP_berd_011_u_w", "", 30, ""},
          {"anzus_CAP_berd_011_u_x", "", 30, ""},
          {"anzus_CAP_char_sniper", "", 30, ""},
          {"anzus_CAP_beanie", "", 30, ""},
          {"anzus_CAP_beanie1", "", 30, ""},
          {"anzus_CAP_beanie2", "", 30, ""},
          {"anzus_CAP_beanie3", "", 30, ""},
          {"anzus_CAP_beanie4", "", 30, ""},
          {"anzus_CAP_beanie5", "", 30, ""},
          {"anzus_CAP_beanie6", "", 30, ""},
          {"anzus_CAP_beanie7", "", 30, ""},
          {"anzus_CAP_beanie8", "", 30, ""},
          {"anzus_CAP_beanie_1", "", 30, ""},
          {"anzus_CAP_beanie_1_a", "", 30, ""},
          {"anzus_CAP_beanie_1_b", "", 30, ""},
          {"anzus_CAP_beanie_1_c", "", 30, ""},
          {"anzus_CAP_beanie_1_d", "", 30, ""},
          {"anzus_CAP_beanie_1_e", "", 30, ""},
          {"anzus_CAP_beanie_1_f", "", 30, ""},
          {"anzus_CAP_beanie_1_g", "", 30, ""},
          {"anzus_CAP_beanie_1_h", "", 30, ""},
          {"anzus_CAP_beanie_1_i", "", 30, ""},
          {"anzus_CAP_beanie_1_j", "", 30, ""},
          {"anzus_CAP_beanie_1_k", "", 30, ""},
          {"anzus_CAP_beanie_1_l", "", 30, ""},
          {"anzus_CAP_beanie_1_m", "", 30, ""},
          {"anzus_CAP_beanie_2_a", "", 30, ""},
          {"anzus_CAP_beanie_2_b", "", 30, ""},
          {"anzus_CAP_beanie_2_c", "", 30, ""},
          {"anzus_CAP_beanie_2_d", "", 30, ""},
          {"anzus_CAP_beanie_2_e", "", 30, ""},
          {"anzus_CAP_beanie_2_f", "", 30, ""},
          {"anzus_CAP_beanie_2_g", "", 30, ""},
          {"anzus_CAP_beanie_2_h", "", 30, ""},
          {"anzus_CAP_beanie_2_i", "", 30, ""},
          {"anzus_CAP_beanie_2_j", "", 30, ""},
          {"anzus_CAP_beanie_2_k", "", 30, ""},
          {"anzus_CAP_beanie_2_l", "", 30, ""},
          {"anzus_CAP_beanie_2_m", "", 30, ""},
          {"anzus_CAP_beanie_2_n", "", 30, ""},
          {"anzus_CAP_beanie_2_o", "", 30, ""},
          {"anzus_CAP_Embacy", "", 30, ""},
          {"anzus_CAP_furcap", "", 30, ""},
          {"anzus_CAP_russelite_hat", "", 30, ""},
          {"anzus_CAP_Headgear", "", 30, ""},
          {"anzus_CAP_Headgear1", "", 30, ""},
          {"anzus_CAP_Headgear_1", "", 30, ""},
          {"anzus_CAP_Headgear1_1", "", 30, ""}
        };

        goggles[] = {
          { "NONE", $STR_C_Remove_goggles, 0, "" },
      		{ "Shadow_Bandana", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 1002" }, //shadowdiv
      		{ "Playboy_Bandana", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2011" },
          { "G_Shades_Black", "", 20, "" },
          { "G_Shades_Blue", "", 20, "" },
          { "G_Shades_Green", "", 20, "" },
          { "G_Shades_Red", "", 20, "" },
          { "G_Sport_Blackred", "", 25, "" },
          { "G_Sport_BlackWhite", "", 25, "" },
          { "G_Sport_Blackyellow", "", 25, "" },
          { "G_Sport_Checkered", "", 25, "" },
          { "G_Sport_Greenblack", "", 25, "" },
          { "G_Sport_Red", "", 25, "" },
          { "G_Lowprofile", "", 20, "" },
          { "G_Squares", "", 20, "" },
          { "G_Aviator", "", 50, "" },
          { "G_Combat", "", 23, "" },
          { "G_Lady_Mirror", "", 26, "" },
          { "G_Lady_Dark", "", 26, "" },
          { "G_Lady_Blue", "", 26, "" },
          { "anzus_p_eyes_000_a", "", 50, "" },
          { "anzus_p_eyes_000_b", "", 50, "" },
          { "anzus_p_eyes_000_c", "", 50, "" },
          { "anzus_p_eyes_000_d", "", 50, "" },
          { "anzus_p_eyes_000_e", "", 50, "" },
          { "anzus_p_eyes_000_f", "", 50, "" },
          { "anzus_p_eyes_000_g", "", 50, "" },
          { "anzus_p_eyes_000_h", "", 50, "" },
          { "anzus_p_eyes_000_i", "", 50, "" },
          { "anzus_p_eyes_000_j", "", 50, "" },
          { "anzus_p_eyes_000_k", "", 50, "" },
          { "anzus_p_eyes_000_l", "", 50, "" },
          { "anzus_p_eyes_000_m", "", 50, "" },
          { "anzus_p_eyes_000_n", "", 50, "" },
          { "anzus_p_eyes_000_o", "", 50, "" },
          { "anzus_p_eyes_001", "", 50, "" },
          { "anzus_Glasses_scarf_a", "", 50, "" },
          { "anzus_Glasses_scarf_b", "", 50, "" },
          { "anzus_Glasses_scarf_c", "", 50, "" },
          { "anzus_Glasses_scarf1_a", "", 50, "" },
          { "anzus_Glasses_scarf1_b", "", 50, "" },
          { "anzus_Glasses_scarf1_c", "", 50, "" },
          { "anzus_Glasses_scarf1_d", "", 50, "" },
          { "anzus_Glasses_scarf2_a", "", 50, "" },
          { "anzus_Glasses_scarf2_b", "", 50, "" },
          { "anzus_Glasses_scarf2_c", "", 50, "" },
          { "anzus_Glasses_scarf2_d", "", 50, "" },
          { "anzus_Glasses_scarf2_e", "", 50, "" },
          { "anzus_Glasses_scarf2_f", "", 50, "" }
        };
        vests[] = {
          { "NONE", $STR_C_Remove_vests, 0, "" },
		  { "AG_NTDVest", "", 5000, "group player getVariable ['gang_id',-1] isEqualTo 320" },
		  { "AG_YakuzaVest", "七点专属定制服装", 5000, "getPlayerUID player in ['76561199014404395']" },
          { "AG_ChauVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 1001" },
          { "AG_SyndicateVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 1002" },
          { "AG_MillersVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 1003" },
          { "AG_BrotherhoodVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 1004" },
          { "AG_LosDCartelVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 1005" },
          { "AG_MillersVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 1006" },
          { "AG_CliqueVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2025" },
          { "AG_UrFatVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 1008" },
          { "AG_HopeVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2028" },
          { "AG_BratvaVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2030" },
          { "AG_atlasVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2008" },
      		{ "AG_SpetsHeavyVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 1025" },
      		{ "AG_LucasVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2048" },
      		{ "AG_NMAVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2031" },
      		{ "AG_ffVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2005" },
			{"AG_PumpedTechVest", "代号007定制服装", 4000, "group player getVariable ['gang_id',-1] isEqualTo 329" },
      		{ "AG_MontanaHeavyVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2018" },
      		{ "AG_BPVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2000" },
      		{ "AG_SCVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 1013" },
      		{ "AG_PMCVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2073" },
      		{ "AG_WPVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2039" },
      		{ "AG_ManarelloVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2087" },
      		{ "AG_MT6Vest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2077" },
      		{ "AG_YakuzaVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2011" },
      		{ "AG_OTVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2092" },
      		{ "AG_TillerVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2088" },
      		{ "AG_OutlawVest2", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2150" },
      		{ "AG_GreenVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2123" },
      		{ "AG_SparkVest", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2086" },
      		{ "AG_DelgadoVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2095" },
      		{ "AG_RussianPlayboysVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2043" },
    			{ "AG_PsiVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 2129" },
    			{ "AG_MongrelVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 3001" },
    			{ "AG_DevilsVest", "", 450, "group player getVariable ['gang_id',-1] isEqualTo 3002" },
    			{ "AG_DiamondVest", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 3042" },
    			{ "AG_CaponeVest", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2153" },
				{ "AG_MDCVest", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 2026" },
				{ "AG_NostraVest", "", 250, "group player getVariable ['gang_id',-1] isEqualTo 3028" },	

//Gang uniform end
          { "V_DeckCrew_brown_F", "", 200, "" },
          { "V_DeckCrew_blue_F", "", 200, "" },
          { "V_DeckCrew_white_F", "", 200, "" },
          { "V_DeckCrew_red_F", "", 200, "" },
          { "V_DeckCrew_violet_F", "", 200, "" },
          { "V_DeckCrew_white_F", "", 200, "" },
          { "V_DeckCrew_yellow_F", "", 200, "" },
          { "V_TacVest_gen_F", "", 300, "" },
          { "AG_CivHeavyVest1", "", 5000, "" },
          { "AG_CivHeavyVest2", "", 5000, "" },
          { "AG_CivHeavyVest3", "", 5000, "" },
          { "AG_CivHeavyVest4", "", 5000, "" },
          { "AG_CivHeavyVest5", "", 5000, "" },
          { "AG_CivHeavyVest6", "", 5000, "" },
          { "AG_CivHeavyVest7", "", 5000, "" },
          { "AG_CivHeavyVest8", "", 5000, "" },
          { "AG_CivHeavyVest9", "", 5000, "" },
          { "AG_CivHeavyVest10", "", 5000, "" }
        };
        backpacks[] = {
          { "NONE", $STR_C_Remove_backpacks, 0, "" },
          { "JD_InvPack", "", 300, "" },
          { "B_OutdoorPack_blk", "", 150, "" },
          { "B_AssaultPack_khk", "", 200, "" },
          { "B_AssaultPack_dgtl", "", 200, "" },
          { "B_AssaultPack_rgr", "", 200, "" },
          { "B_AssaultPack_sgg", "", 200, "" },
          { "B_AssaultPack_blk", "", 200, "" },
          { "B_AssaultPack_cbr", "", 200, "" },
          { "B_AssaultPack_mcamo", "", 200, "" },
          { "B_AssaultPack_tna_f", "", 200, "" },
          { "B_TacticalPack_oli", "", 200, "" },
          { "B_Kitbag_mcamo", "", 300, "" },
          { "B_Kitbag_sgg", "", 300, "" },
          { "B_Kitbag_cbr", "", 300, "" },
          { "B_FieldPack_blk", "", 400, "" },
          { "B_FieldPack_ocamo", "", 400, "" },
          { "B_FieldPack_oucamo", "", 400, "" },
          { "B_FieldPack_ghex_f", "", 400, "" },
          { "B_Bergen_sgg", "", 500, "" },
          { "B_Bergen_mcamo", "", 500, "" },
          { "B_Bergen_rgr", "", 500, "" },
          { "B_Bergen_blk", "", 500, "" },
          { "B_Carryall_ocamo", "", 550, "" },
          { "B_Carryall_oucamo", "", 550, "" },
          { "B_Carryall_mcamo", "", 550, "" },
          { "B_Carryall_oli", "", 550, "" },
          { "B_Carryall_khk", "", 550, "" },
          { "B_Carryall_cbr", "", 550, "" },
          { "B_Carryall_ghex_f", "", 650, "" },
          { "B_Bergen_dgtl_f", "", 650, "" },
          { "B_AssaultPack_mcamo", "", 200, "" },
          { "B_TacticalPack_oli", "", 30, "" },
          { "B_Kitbag_mcamo", "", 300, "" },
          { "B_Kitbag_sgg", "", 300, "" },
          { "B_Kitbag_cbr", "", 300, "" },
          { "B_FieldPack_blk", "", 500, "" },
          { "B_FieldPack_ocamo", "", 500, "" },
          { "B_FieldPack_oucamo", "", 500, "" },
          { "B_Bergen_sgg", "", 650, "" },
          { "B_Bergen_mcamo", "", 650, "" },
          { "B_Bergen_rgr", "", 650, "" },
          { "B_Bergen_blk", "", 650, "" },
          { "B_Carryall_ocamo", "", 750, "" },
          { "B_Carryall_oucamo", "", 750, "" },
          { "B_Carryall_mcamo", "", 750, "" },
          { "B_Carryall_oli", "", 750, "" },
          { "B_Carryall_khk", "", 750, "" },
          { "B_Carryall_cbr", "", 750, "" }
        };
    };

    class cop {
        title = "STR_Shops_C_Police";
        conditions = "";
        side = "cop";
         uniforms[] = {
          { "NONE", $STR_C_Remove_uniforms, 0, "" },
          //DOC
          { "AG_Corrections1", "", 20, "call life_copdept in [1,5,7]" },
          { "AG_Corrections2", "", 20, "call life_copdept in [1,5,7]" },
          { "AG_Corrections3", "", 20, "call life_copdept in [1,5,7]" },
          { "AG_Corrections4", "", 20, "call life_copdept in [1,5,7]" },
          { "AG_Corrections5", "", 20, "call life_copdept in [1,5,7]" },
          { "AG_Corrections6", "", 20, "call life_copdept in [1,5,7]" },
      	  { "JD_Swat", "CRT", 20, "call life_copdept in [1,5,7]" },
		  { "AG_DChief", "局长制服", 20, "getPlayerUID player in ['76561198901125463']" },
          //regular police
          { "AL_Police1", "普通警察制服", 20, "call life_copdept in [2,6,7]" },
          { "AL_Police2", "高级警察制服", 20, "call life_copdept in [2,6,7]" },
          { "AL_Police4", "警长制服", 20, "call life_copdept in [2,6,7]" },
          { "AL_Police5", "警督制服", 20, "call life_copdept in [2,6,7]" },
          { "AL_Police6", "警监制服", 20, "call life_copdept in [2,6,7]" },
      		{ "AL_Police16", "警司制服", 20, "call life_copdept in [2,6,7]" },
      	  { "AL_Police17", "总警司制服", 20, "call life_copdept in [2,6,7]" },
          { "EF_HMP_1", "Kain", 20, "call life_copdept in [7]" },
          { "PAT_suit2", "Flynn", 20, "call life_copdept in [7]" },
          { "female_police", "", 20, "call life_copdept in [2,6,7]" },
      		{ "Girl_Police_Avalon", "Reaper Only", 20, "call life_copdept in [1,5,7]" },
          //IA
      		{ "AG_IAUniform", "", 20, "call life_copdept in [4,7]" },
          //Sheriff
          { "JD_5star", "", 20, "call life_copdept in [3] && call life_coplevel >= 8" },
          { "JD_4star", "", 20, "call life_copdept in [3] && call life_coplevel >= 8" },
        	{ "JD_Captain", "", 20, "call life_copdept in [3] && call life_coplevel >= 8" },
          { "JD_Lieutenant", "", 20, "call life_copdept in [3] && call life_coplevel >= 7" },
          { "JD_Sergeant", "", 20, "call life_copdept in [3] && call life_coplevel >= 5" },
          { "JD_Deputy", "", 20, "call life_copdept in [3] && call life_coplevel >= 3" },
      		{ "AG_SheriffJacket", "", 20, "call life_copdept in [3] && call life_coplevel >= 7" },
          //BOI
          { "AG_BOIJacketBlack", "", 20, "call life_copdept in [5,7]" },
          { "AG_BOIJacketBlue", "", 20, "call life_copdept in [5,7]" },
          { "AG_BOIJacketPurple", "", 20, "call life_copdept in [5,7]" },
          //SWAT
      		{ "swat_uni_black", "", 20, "call life_copdept in [6,7]" },
      	  { "swat_uni_blue", "", 20, "call life_copdept in [6,7]" },
      	  { "swat_uni_mblack", "", 20, "call life_copdept in [6,7]" },
      	  { "swat_uni_odgreen", "", 20, "call life_copdept in [6,7]" },
          //Special
          { "AG_PoliceWetsuit", "", 20, "" }
        };
        headgear[] = {
          { "NONE", $STR_C_Remove_headgear, 0, "" },
			    //Patrol
			{ "AG_hwp_hat", "局长帽", 20, "getPlayerUID player in ['76561198901125463']" },
      		{ "JD_SheriffHat_Black", "Corrections Hat", 20, "call life_copdept in [1,5,7]" },
    		  { "police_helmet", "CRT Helmet", 20, "call life_copdept in [1,5,7]" },
    			{ "jf_police_hat_02", "普通警帽", 20, "call life_copdept in [2,6,7]" },
					{ "AL_BOIBeret", "机动部队(专用", 20, "call life_copdept in [2,6,7]" },
					{ "JD_BlackCap", "轻便帽子", 20, "call life_copdept in [2,6,7]" },
    			{ "Swat_MBLK_Helmet", "防暴盔(大型事件用)", 20, "call life_copdept in [2,6,7]" },
      	  { "jf_police_hat_01", "管理层(专用)", 20, "call life_copdept in [2,6,7]" },
      		{ "V12_CASQUE_1_BLEU", "Motorbike Helmet", 20, "call life_copdept in [2,6,7]" },
      		{ "H_PilotHelmetHeli_B", "Air1 Helmet", 20, "call life_copdept in [2,6,7]" },
      		{ "H_Beret_02", "", 20, "call life_coplevel >= 6" },
      		{ "H_Beret_02", "", 20, "call life_coplevel >= 7" },
      		{ "H_Beret_gen_F", "", 20, "call life_coplevel >= 8" },
      		{ "H_Beret_Colonel", "", 20, "call life_coplevel >= 9" },
          { "H_Beret_blk", "", 20, "call life_copdept in [7]" },
      		{ "UB_Custom_Aladeenn_BERET", "Phantom", 20, "call life_copdept in [7]" },
      		{ "police_furag", "Radeno", 20, "call life_copdept in [7]" },
      		{ "chief_furag", 20, "call life_copdept in [7]" },
    			{ "JD_CowboyHat_Brown", "Woody Hat", 20, "call life_copdept in [7]" },
					{ "IA_Headgear", "", 20, "call life_copdept in [4,7]" },
          //Boi
          { "CID_Cap_Blk", "", 300, "call life_copdept in [5,7]" },
          { "CID_Cap_Grn", "", 300, "call life_copdept in [5,7]" },
          { "CID_Cap_Tan", "", 300, "call life_copdept in [5,7]" },

      		{ "Kangaro0_MarshalH", "", 300, "call life_copdept in [4,7]" },
      		{ "Kangaro0_Marshal_Red", "", 300, "call life_copdept in [4,7]" },
      		{ "Kangaro0_Marshal_Black", "", 300, "call life_copdept in [4,7]" },
      		{ "Kangaro0_Marshal_Green", "", 300, "call life_copdept in [4,7]" },
      		{ "Kangaro0_Marshal_Navy", "", 300, "call life_copdept in [4,7]" },
      		{ "Kangaro0_Marshal_Tan", "", 300, "call life_copdept in [4,7]" },
      		{ "Kangaro0_Marshal_Grey", "", 300, "call life_copdept in [4,7]" },

          //Sheriff
          { "JD_SheriffHat_Green", "", 20, "call life_copdept in [3] && call life_coplevel >= 3" },
          { "JD_SheriffHat_Tan", "", 20, "call life_copdept in [3] && call life_coplevel >= 3" },
          { "JD_SherrifCap", "", 20, "call life_copdept in [3] && call life_coplevel >= 3" },
          { "JD_SertHat", "", 20, "call life_copdept in [3] && call life_coplevel >= 8" },

			    //CRT
      		{ "SWAT_Blk_Boonie", "CRT ONLY", 300, "call life_coplevel >= 5 && call life_copdept in [1,7,8]" },
      		{ "Swat_blk_Helmet", "CRT ONLY", 300, "call life_coplevel >= 5 && call life_copdept in [1,7,8]" },
          //SWAT
          { "SWAT_Beret", "", 300, "call life_copdept in [6,7]" },
      		{ "SWAT_Blk_Boonie", "", 300, "call life_copdept in [6,7]" },
      		{ "Swat_blk_Helmet", "", 300, "call life_copdept in [6,7]" },
      		{ "SWAT_Blue_Boonie", "", 300, "call life_copdept in [6,7]" },
      		{ "Swat_blue_Helmet", "", 300, "call life_copdept in [6,7]" },
      		{ "SWAT_MBlk_Boonie", "", 300, "call life_copdept in [6,7]" },
      		{ "Swat_MBLK_Helmet", "", 300, "call life_copdept in [6,7]" },
      		{ "SWAT_OD_Boonie", "", 300, "call life_copdept in [6,7]" },
      		{ "Swat_OD_Helmet", "", 300, "call life_copdept in [6,7]" },
    			{ "V12_ECHARPE2", "Rick", 300, "call life_copdept in [6,7] && call life_coplevel >= 6" },
    			{ "V12_ECHARPE3", "Rick", 300, "call life_copdept in [6,7] && call life_coplevel >= 6" },
      		{ "SWAT_Shemagh", "", 300, "call life_copdept in [6,7]" }
        };
        goggles[] = {
          { "NONE", $STR_C_Remove_goggles, 0, "" },
          //Sheriff
          { "JD_Tie1", "", 20, "call life_copdept in [3] && call life_coplevel >= 8" },
          { "JD_Tie", "", 20, "call life_copdept in [3] && call life_coplevel >= 3" },
          { "JD_Mask", "", 20, "call life_copdept in [3] && call life_coplevel >= 8" },
			      { "anzus_CAP_berd_003_u_glasses", "CRT ONLY", 20, "call life_copdept in [1] && call life_coplevel >= 5" },
          { "A3MT_Police_Ohrstecker", "Full Screen NVG", 100, "" },
          { "G_Shades_Black", "", 20, "" },
          { "G_Shades_Blue", "", 20, "" },
          { "G_Shades_Green", "", 20, "" },
          { "G_Shades_Red", "", 20, "" },
          { "G_Sport_Blackred", "", 25, "" },
          { "G_Sport_BlackWhite", "", 25, "" },
          { "G_Sport_Blackyellow", "", 25, "" },
          { "G_Sport_Checkered", "", 25, "" },
          { "G_Sport_Greenblack", "", 25, "" },
          { "G_Sport_Red", "", 25, "" },
          { "G_Lowprofile", "", 20, "" },
          { "G_Squares", "", 20, "" },
          { "G_Aviator", "", 50, "" },
          { "G_Combat", "", 23, "" },
          { "G_Lady_Mirror", "", 26, "" },
          { "G_Lady_Dark", "", 26, "" },
          { "G_Lady_Blue", "", 26, "" },
          { "anzus_p_eyes_000_a", "", 50, "" },
          { "anzus_p_eyes_000_b", "", 50, "" },
          { "anzus_p_eyes_000_c", "", 50, "" },
          { "anzus_p_eyes_000_d", "", 50, "" },
          { "anzus_p_eyes_000_e", "", 50, "" },
          { "anzus_p_eyes_000_f", "", 50, "" },
          { "anzus_p_eyes_000_g", "", 50, "" },
          { "anzus_p_eyes_000_h", "", 50, "" },
          { "anzus_p_eyes_000_i", "", 50, "" },
          { "anzus_p_eyes_000_j", "", 50, "" },
          { "anzus_p_eyes_000_k", "", 50, "" },
          { "anzus_p_eyes_000_l", "", 50, "" },
          { "anzus_p_eyes_000_m", "", 50, "" },
          { "anzus_p_eyes_000_n", "", 50, "" },
          { "anzus_p_eyes_000_o", "", 50, "" },
          { "anzus_p_eyes_001", "", 50, "" },
			    { "JD_Mask", "SWAT Gas Mask", 10, "call life_copdept in [5,6,7]" },
          { "G_Diving", "", 10, "call life_copdept in [5,6,7]" },
          { "G_Bandanna_blk", "", 10, "call life_copdept in [5,6,7]" },
          { "G_Balaclava_TI_blk_F", "", 40, "call life_copdept in [5,6,7]" },

          //Keenun Swat Stuff
          { "G_Bandanna_oli", "", 10, "call life_copdept in [6,7]" },
          { "G_Bandanna_blk", "", 10, "call life_copdept in [6,7]" },
          { "G_Bandanna_beast", "", 10, "call life_copdept in [6,7]" },
          { "G_Bandanna_aviator", "", 10, "call life_copdept in [6,7]" },
          { "G_Balaclava_oli", "", 10, "call life_copdept in [6,7]" },
          { "G_Balaclava_blk", "", 10, "call life_copdept in [6,7]" },
          { "TRYK_R_CAP_BLK", "", 10, "call life_copdept in [6,7]" },
          { "TRYK_R_CAP_OD_US", "", 10, "call life_copdept in [6,7]" },
          { "TRYK_SpsetG_Glasses", "", 10, "call life_copdept in [6,7]" }
        };
        vests[] = {
          { "NONE", $STR_C_Remove_vests, 0, "" },
          //sheriff
          { "AL_PoliceVest", "", 600, "call life_copdept in [3] && call life_coplevel >= 3" },
          { "JD_Vest1", "", 600, "call life_copdept in [3] && call life_coplevel >= 3" },
          { "V_CarrierRigKBT_01_light_Olive_F", "", 600, "call life_copdept in [3] && call life_coplevel >= 3" },
          { "V_CarrierRigKBT_01_Olive_F", "", 600, "call life_copdept in [3] && call life_coplevel >= 3" },
          { "AG_SheriffVestBrown", "", 600, "call life_copdept in [3] && call life_coplevel >= 3" },
          { "AG_SheriffVestBrownk9", "", 600, "call life_copdept in [3] && call life_coplevel >= 8" },
          { "AG_SheriffVest", "", 600, "call life_copdept in [3] && call life_coplevel >= 9" },
          { "AG_SheriffVestk9", "", 600, "call life_copdept in [3] && call life_coplevel >= 9" },
          { "JD_Vest10", "", 600, "call life_copdept in [3] && call life_coplevel >= 3" },

          { "JD_Vest8", "", 600, "" },
          { "AG_PatrolVestNew", "", 600, "call life_copdept in [2,5,6,7]" },
          { "AG_CorrectionsHeavyVest", "", 600, "call life_copdept in [1,5,7]" },
        	{ "AG_CRTHeavyVest", "CRT", 600, "call life_copdept in [1,5,7]" },
          { "AL_PoliceVest", "", 600, "call life_copdept in [2,6,7]" },
          { "AG_PoliceHeavyVest", "", 600, "call life_copdept in [2,5,6,7]" },
          { "AG_FTOHeavyGreenVest", "", 600, "call life_copdept in [2,6,7]" },
          { "AG_InternalAffairsHeavyVest", "", 600, "call life_copdept in [4,7]" },
          { "JD_Belt4", "", 600, "call life_copdept in [5,7]" },
          { "AG_PoliceRebreatherHeavyVest", "", 100, "" },
          //BOI
  				{ "AG_BOIHeavyVest", "", 600, "call life_copdept in [5,7,8]" },
      	  { "JD_Belt3", "", 600, "call life_copdept in [5,7,8]" },
      		{ "JD_Belt4", "", 600, "call life_copdept in [5,7,8]" },
    			{ "AG_CivHeavyVest1", "", 5000, "call life_copdept in [5,7,8]" },
    			{ "AG_CivHeavyVest2", "", 5000, "call life_copdept in [5,7,8]" },
    			{ "AG_CivHeavyVest3", "", 5000, "call life_copdept in [5,7,8]" },
    			{ "AG_CivHeavyVest4", "", 5000, "call life_copdept in [5,7,8]" },
    			{ "AG_CivHeavyVest5", "", 5000, "call life_copdept in [5,7,8]" },
    			{ "AG_CivHeavyVest6", "", 5000, "call life_copdept in [5,7,8]" },
    			{ "AG_CivHeavyVest7", "", 5000, "call life_copdept in [5,7,8]" },
    			{ "AG_CivHeavyVest8", "", 5000, "call life_copdept in [5,7,8]" },
    			{ "AG_CivHeavyVest9", "", 5000, "call life_copdept in [5,7,8]" },

          //SWAT
      		{ "AG_HeavyVest", "", 600, "call life_copdept in [6,7]" },
      		{ "swat_vest_blue", "", 600, "call life_copdept in [6,7]" },
      		{ "swat_vest_multi_blk", "", 600, "call life_copdept in [6,7]" },
      		{ "swat_vest_od", "", 600, "call life_copdept in [6,7]" }
        };
        backpacks[] = {
          { "NONE", $STR_C_Remove_backpacks, 0, "" },
          { "officer_belt", "Police Belt", 70, "" },
      		{ "JD_InvPack", "Invisible Belt(Do not abuse or you lose)", 70, "" }
        };
    };

    class dive {
        title = "STR_Shops_C_Diving";
        conditions = "license_civ_dive";
        side = "civ";
        uniforms[] = {
          { "NONE", $STR_C_Remove_uniforms, 0, "" },
          { "U_B_Wetsuit", "", 200, "" }
        };
        headgear[] = {
          { "NONE", $STR_C_Remove_headgear, 0, "" }
        };
        goggles[] = {
          { "NONE", $STR_C_Remove_goggles, 0, "" },
          { "G_Diving", "", 10, "" }
        };
        vests[] = {
          { "NONE", $STR_C_Remove_vests, 0, "" },
          { "V_RebreatherB", "", 100, "" }
        };
        backpacks[] = {
          { "NONE", $STR_C_Remove_backpacks, 0, "" }
        };
    };

    class cop_boat {
        title = "STR_Shops_C_Diving";
        conditions = "";
        side = "cop";
        uniforms[] = {
          { "NONE", $STR_C_Remove_uniforms, 0, "" },
          { "U_B_Wetsuit", "", 200, "" }
        };
        headgear[] = {
          { "NONE", $STR_C_Remove_headgear, 0, "" }
        };
        goggles[] = {
          { "NONE", $STR_C_Remove_goggles, 0, "" },
          { "G_Diving", "", 10, "" }
        };
        vests[] = {
          { "NONE", $STR_C_Remove_vests, 0, "" },
          { "V_RebreatherB", "", 100, "" }
        };
        backpacks[] = {
          { "NONE", $STR_C_Remove_backpacks, 0, "" },
          { "officer_belt", "", 200, "" }
        };
    };

    class gun_clothing {
        title = "STR_Shops_C_Gun";
        conditions = "license_civ_gun";
        side = "civ";
        uniforms[] = {
          { "NONE", $STR_C_Remove_uniforms, 0, "" },
          { "U_Competitor", "", 20, "" },
          { "U_C_Man_casuAG_2_F", "", 20, "" },
          { "U_C_Poor_1", "", 20, "" }
        };
        headgear[] = {
          { "NONE", $STR_C_Remove_headgear, 0, "" },
          { "H_Cap_marshal", "", 10, "" }
        };
        vests[] = {
          { "NONE", $STR_C_Remove_vests, 0, "" },
          { "V_DeckCrew_brown_F", "", 200, "" },
          { "V_DeckCrew_blue_F", "", 200, "" },
          { "V_DeckCrew_white_F", "", 200, "" },
          { "V_DeckCrew_red_F", "", 200, "" },
          { "V_DeckCrew_violet_F", "", 200, "" },
          { "V_DeckCrew_white_F", "", 200, "" },
          { "V_DeckCrew_yellow_F", "", 200, "" },
          { "V_TacVest_gen_F", "", 300, "" },
          { "V_Press_F", "", 300, "" }
        };
        backpacks[] = {
          { "NONE", $STR_C_Remove_backpacks, 0, "" },
          { "anzus_backpack_j", "", 100, "" },
          { "anzus_backpack_k", "", 100, "" },
          { "anzus_backpack_a", "", 100, "" },
          { "anzus_backpack_d", "", 100, "" },
          { "anzus_backpack_h", "", 100, "" }
        };
    };

    class med_clothing {
        title = "STR_MAR_EMS_Clothing_Shop";
        conditions = "";
        side = "med";
        uniforms[] = {
          { "NONE", $STR_C_Remove_uniforms, 0, "" },
			    { "JD_FDPlain", "", 30, "" },
          { "ADT_EMS_Uniform2", "", 30, "" },
          { "KMD_Volunteer_Uniform", "", 30, "" },
          { "KMD_Probie_Uniform", "", 30, "" },
          { "KMD_Paramedic_Uniform", "", 30, "" },
          { "KMD_AdvancedParamedic_Uniform", "", 30, "" },
          { "KMD_AsstCommissioner_Uniform", "", 30, "" },
          { "KMD_Captain_Uniform", "", 30, "" },
          { "KMD_Commissioner_Uniform", "", 30, "" },
          { "KMD_DeptCommissioner_Uniform", "", 30, "" },
          { "KMD_FieldCommander_Uniform", "", 30, "" },
          { "KMD_Lieutenant_Uniform", "", 30, "" },
          { "KMD_MedicalTechnician_Uniform", "", 30, "" },
          { "KMD_Superintendent_Uniform", "", 30, "" },
          { "ADT_AircrewCoveralls", "", 100, "" },
			    { "JD_Fireman", "", 100, "" },
          { "vvv_traje_bombero_2", "", 30, "" },
          { "vvv_traje_bombero", "", 30, "" },
          { "rds_uniform_doctor", "", 30, "" },
          { "ADT_EMS_Uniform12", "", 30, "" },
          { "UB_EMS_Head_Medic_suit", "", 100, "" },
			    { "AG_EMSWetsuit", "", 100, "" },
			    { "U_C_CBRN_Suit_01_White_F", "", 100, "" }
        };
        headgear[] = {
          { "NONE", $STR_C_Remove_headgear, 0, "" },
          { "H_Cap_grn", "EMT G1 Cap", 10, "" },
          { "H_Cap_blu", "EMT G2/3 Cap", 10, "" },
          { "H_Cap_red", "EMT G4/5 Cap", 10, "" },
          { "H_Cap_red", "Fire Casual", 30, "" },
      		{ "EMSBeret1_Headgear", "EMS B1", 10, "" },
      		{ "EMSBeret2_Headgear", "EMS B2", 10, "" },
      		{ "EMSBeret3_Headgear", "EMS B3", 10, "" },
      		{ "EMS1_Headgear", "EMS C1", 10, "" },
      		{ "EMS2_Headgear", "EMS C2", 10, "" },
      		{ "JD_FirehatBlack", "Fire Hat Black", 30, "" },
      		{ "JD_FirehatRed", "Fire Hat Red", 30, "" }
        };
        goggles[] = {
          { "NONE", $STR_C_Remove_goggles, 0, "" },
          { "JD_Mask", "Fire PPE Mask", 10, "" },
          { "G_I_Diving", "S&R Diving Goggles", 10, "" },
          { "G_Respirator_blue_F", "", 10, "" },
          { "G_Respirator_white_F", "", 10, "" },
          { "G_Respirator_yellow_F", "", 10, "" },
          { "G_Shades_Black", "", 20, "" },
          { "G_Shades_Blue", "", 20, "" },
          { "G_Shades_Green", "", 20, "" },
          { "G_Shades_Red", "", 20, "" },
          { "G_Sport_Blackred", "", 25, "" },
          { "G_Sport_BlackWhite", "", 25, "" },
          { "G_Sport_Blackyellow", "", 25, "" },
          { "G_Sport_Checkered", "", 25, "" },
          { "G_Sport_Greenblack", "", 25, "" },
          { "G_Sport_Red", "", 25, "" },
          { "G_Lowprofile", "", 20, "" },
          { "G_Squares", "", 20, "" },
          { "G_Aviator", "", 50, "" },
          { "G_Combat", "", 23, "" },
          { "G_Lady_Mirror", "", 26, "" },
          { "G_Lady_Dark", "", 26, "" },
          { "G_Lady_Blue", "", 26, "" },
          { "G_RegulatorMask_F", "", 26, "" },
          { "anzus_p_eyes_000_a", "", 50, "" },
          { "anzus_p_eyes_000_b", "", 50, "" },
          { "anzus_p_eyes_000_c", "", 50, "" },
          { "anzus_p_eyes_000_d", "", 50, "" },
          { "anzus_p_eyes_000_e", "", 50, "" },
          { "anzus_p_eyes_000_f", "", 50, "" },
          { "anzus_p_eyes_000_g", "", 50, "" },
          { "anzus_p_eyes_000_h", "", 50, "" },
          { "anzus_p_eyes_000_i", "", 50, "" },
          { "anzus_p_eyes_000_j", "", 50, "" },
          { "anzus_p_eyes_000_k", "", 50, "" },
          { "anzus_p_eyes_000_l", "", 50, "" },
          { "anzus_p_eyes_000_m", "", 50, "" },
          { "anzus_p_eyes_000_n", "", 50, "" },
          { "anzus_p_eyes_000_o", "", 50, "" },
          { "anzus_p_eyes_001", "", 50, "" },
          { "anzus_Glasses_scarf_a", "", 50, "" },
          { "anzus_Glasses_scarf_b", "", 50, "" },
          { "anzus_Glasses_scarf_c", "", 50, "" },
          { "anzus_Glasses_scarf1_a", "", 50, "" },
          { "anzus_Glasses_scarf1_b", "", 50, "" },
          { "anzus_Glasses_scarf1_c", "", 50, "" },
          { "anzus_Glasses_scarf1_d", "", 50, "" },
          { "anzus_Glasses_scarf2_a", "", 50, "" },
          { "anzus_Glasses_scarf2_b", "", 50, "" },
          { "anzus_Glasses_scarf2_c", "", 50, "" },
          { "anzus_Glasses_scarf2_d", "", 50, "" },
          { "anzus_Glasses_scarf2_e", "", 50, "" },
          { "anzus_Glasses_scarf2_f", "", 50, "" }
        };
        vests[] = {
          { "NONE", $STR_C_Remove_vests, 0, "" },
			    { "AG_EMSRebreatherHeavyVest", "S&R Diving Vest", 10, "" },
          { "JD_Medic", "", 10, "" },
          { "travis_EMTVest", "", 10, "" },
          { "travis_CommandVest", "", 10, "" },
          { "travis_RideAlongVest", "", 10, "" },
          { "travis_TraineeVest", "", 10, "" },
          { "travis_SARVest", "", 10, "" }
        };
        backpacks[] = {
          { "NONE", $STR_C_Remove_backpacks, 0, "" },
          { "JD_InvPack", "EMS Invisible Pack", 10, "" },
          { "B_SCBA_01_F", "Self Contained Breathing Apparatus", 10, "" }
        };
    };

    class bike {
        title = "STR_Shops_C_bike";
        conditions = "";
        side = "civ";
        uniforms[] = {
          { "NONE", $STR_C_Remove_uniforms, 0, "" },
          { "vvv_traje_motox_02_6", "", 50, "" },
          { "vvv_traje_motox_02_2", "", 50, "" },
          { "vvv_traje_motox_02_5", "", 50, "" },
          { "vvv_traje_motox_02_4", "", 50, "" },
          { "vvv_traje_motox_02_8", "", 50, "" },
          { "vvv_traje_motox_02", "", 50, "" },
          { "vvv_traje_motox_02_3", "", 50, "" }
        };
        headgear[] = {
          { "NONE", $STR_C_Remove_headgear, 0, "" },
          { "V12_CROSS", "", 100, "" },
          { "V12_CROSS1", "", 100, "" },
          { "V12_CROSS2", "", 100, "" },
          { "V12_CROSS3", "", 100, "" },
          { "V12_CROSS4", "", 100, "" },
          { "V12_CROSS5", "", 100, "" },
          { "V12_CROSS6", "", 200, "" },
          { "V12_CROSS7", "", 200, "" },
          { "V12_CROSS8", "", 200, "" }
        };
    };

    class gangster {
        title = "STR_Shops_C_Gang";
        license = "";
        side = "civ";
        uniforms[] = {
          { "NONE", "Remove Uniform", 0, ""},
          { "PAT_nigga", "", 500, ""},
          { "PAT_nigga2_1", "", 500, ""},
          { "PAT_nigga3", "", 500, ""},
          { "PAT_nigga2_3", "", 500, ""},
          { "PAT_nigga6", "", 500, ""},
          { "PAT_nigga2_6", "", 500, ""},
          { "PAT_nigga2", "", 500, ""},
          { "PAT_nigga2_2", "", 500, ""},
          { "PAT_nigga4", "", 500, ""},
          { "PAT_nigga2_4", "", 500, ""},
          { "PAT_nigga5", "", 500, ""},
          { "PAT_nigga2_5", "", 500, ""},
          { "kw_yuri_jogging_1", "", 500, ""},
          { "TRYK_U_B_BLK_T_BG_WH", "", 500, ""},
          { "TRYK_U_B_RED_T_BG_BR", "", 500, ""},
          { "TRYK_U_B_BLK_T_BG_BK", "", 500, ""},
          { "anzus_uniform_jbib_008_a", "GUCCI MINK M8", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_aa", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ab", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ac", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ad", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ae", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_af", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_b", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ba", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_bb", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_bc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_bd", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_be", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_bf", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_c", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ca", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_cb", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_cc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_cd", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ce", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_cf", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_d", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_da", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_db", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_dc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_dd", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_de", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_df", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_e", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ea", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_eb", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ec", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ed", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ee", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ef", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_f", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_fa", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_fb", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_fc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_fd", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_fe", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ff", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_g", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ga", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_gb", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_gc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_gd", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ge", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_h", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ha", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_hb", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_hc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_hd", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_he", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_hf", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_i", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ia", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ib", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ic", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_id", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ie", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_if", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_j", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ja", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_jb", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_jc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_jd", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_je", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_jf", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_k", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ka", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_kb", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_kc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_kd", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ke", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_kf", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_l", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_la", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_lb", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_lc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ld", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_le", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_lf", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_m", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ma", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_mb", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_mc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_md", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_me", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_mf", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_n", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_na", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_nb", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_nc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_nd", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ne", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_nf", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_o", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_oa", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_ob", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_oc", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_od", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_oe", "", 1000, {"", "", -1} },
          { "anzus_uniform_jbib_008_of", "", 1000, {"", "", -1} }
        };
        headgear[] = {
          { "NONE", "Remove Hat", 0, ""},
          { "pat_cap4_nigga", "", 50, ""},
          { "pat_cap4_nigga_back_low", "", 50, ""},
          { "pat_cap4_front", "", 50, ""},
          { "pat_cap10_front", "", 50, ""},
          { "pat_cap4_nigga_back", "", 50, ""},
          { "pat_cap4_back", "", 50, ""},
          { "pat_cap10_back", "", 50, ""},
          { "pat_cap6_nigga", "", 50, ""},
          { "pat_cap6_nigga_back_low", "", 50, ""},
          { "pat_cap6_front", "", 50, ""},
          { "pat_cap12_front", "", 50, ""},
          { "pat_cap6_nigga_back", "", 50, ""},
          { "pat_cap6_back", "", 50, ""},
          { "pat_cap12_back", "", 50, ""},
          { "pat_durag_white", "", 50, ""},
          { "pat_durag_black", "", 50, ""},
          { "pat_cap2_nigga", "", 50, ""},
          { "pat_cap2_nigga_back_low", "", 50, ""},
          { "pat_cap2_front", "", 50, ""},
          { "pat_cap8_front", "", 50, ""},
          { "pat_cap2_nigga_back", "", 50, ""},
          { "pat_cap2_back", "", 50, ""},
          { "pat_cap8_back", "", 50, ""},
          { "pat_cap5_nigga", "", 50, ""},
          { "pat_cap5_nigga_back_low", "", 50, ""},
          { "pat_cap5_front", "", 50, ""},
          { "pat_cap11_front", "", 50, ""},
          { "pat_cap5_nigga_back", "", 50, ""},
          { "pat_cap5_back", "", 50, ""},
          { "pat_cap11_back", "", 50, ""},
          { "pat_cap3_nigga", "", 50, ""},
          { "pat_cap3_nigga_back_low", "", 50, ""},
          { "pat_cap3_front", "", 50, ""},
          { "pat_cap9_front", "", 50, ""},
          { "pat_cap3_nigga_back", "", 50, ""},
          { "pat_cap3_back", "", 50, ""},
          { "pat_cap9_back", "", 50, ""},
          { "pat_cap_nigga", "", 50, ""},
          { "pat_cap_nigga_back_low", "", 50, ""},
          { "pat_cap_front", "", 50, ""},
          { "pat_cap7_front", "", 50, ""},
          { "pat_cap_nigga_back", "", 50, ""},
          { "pat_cap_back", "", 50, ""},
          { "pat_cap7_back", "", 50, ""},
          { "A3L_gangster_hat", "", 50, ""},
          { "bike_berd_003_a1", "", 50, ""},
          { "bike_berd_003_a", "", 50, ""},
          { "bike_berd_003_b", "", 50, ""},
          { "bike_berd_003_b1", "", 50, ""},
          { "bike_berd_003_f", "", 50, ""},
          { "bike_berd_003_f1", "", 50, ""},
          { "bike_berd_003_g", "", 50, ""},
          { "bike_berd_003_g1", "", 50, ""},
          { "bike_berd_003_i", "", 50, ""},
          { "bike_berd_003_i1", "", 50, ""},
          { "V12_BONNET_BLANC", "", 250, ""},
          { "V12_BONNET_BLEU", "", 250, ""},
          { "V12_BONNET_CAMO", "", 250, ""},
          { "V12_BONNET_CAMO2", "", 250, ""},
          { "V12_BONNET_GUCCI", "", 250, ""},
          { "V12_BONNET_GUCCI1", "", 250, ""},
          { "V12_BONNET_LV", "", 250, ""},
          { "V12_BONNET_LV1", "", 250, ""},
          { "V12_BONNET_LV3", "", 250, ""},
          { "V12_BONNET_LV4", "", 250, ""},
          { "V12_BONNET_LV2", "", 250, ""},
          { "V12_BONNET_NOIR", "", 250, ""},
          { "V12_BONNET_ORANGE", "", 250, ""},
          { "V12_BONNET_ROUGE", "", 250, ""},
          { "V12_CASQUETTE_CAMO1", "", 250, ""},
          { "V12_CASQUETTE_CAMO2", "", 250, ""},
          { "V12_CASQUETTE_CAMO", "", 250, ""},
          { "V12_CASQUETTE_GUCCI", "", 250, ""},
          { "V12_CASQUETTE_GUCCI1", "", 250, ""},
          { "V12_CASQUETTE_GUCCI2", "", 250, ""},
          { "V12_CASQUETTE_LV3", "", 250, ""},
          { "V12_CASQUETTE_LV4", "", 250, ""},
          { "V12_CASQUETTE_LV", "", 250, ""},
          { "V12_CASQUETTE_NOIR", "", 250, ""},
          //head scalf
          { "V12_ECHARPE", "", 1000, ""},
          { "V12_ECHARPE1", "", 1000, ""},
          { "V12_ECHARPE2", "", 1000, ""},
          { "V12_ECHARPE3", "", 1000, ""},
          { "V12_ECHARPE4", "", 1000, ""},
          { "V12_ECHARPE5", "", 1000, ""},
          { "V12_ECHARPE6", "", 1000, ""},
          { "V12_ECHARPE7", "", 1000, ""},
          { "V12_ECHARPE8", "", 1000, ""},
          { "V12_ECHARPE9", "", 1000, ""},
          { "V12_ECHARPE10", "", 1000, ""},
          { "V12_ECHARPE11", "", 1000, ""},
          { "V12_ECHARPE12", "", 1000, { "", "", -1 } }
        };
        goggles[] = {
          { "NONE", "Remove Glasses", 0, ""},
          { "nigga_platok", "", 50, ""},
          { "nigga_platok4", "", 50, ""},
          { "nigga_platok3", "", 50, ""},
          { "nigga_platok6", "", 50, ""},
          { "nigga_platok5", "", 50, ""},
          { "nigga_platok2", "", 50, ""},
          { "nigga_gog", "", 50, ""},
          { "nigga_platok7", "", 50, ""},
          { "nigga_platok10", "", 50, ""},
          { "nigga_platok9", "", 50, ""},
          { "nigga_platok12", "", 50, ""},
          { "nigga_platok11", "", 50, ""},
          { "nigga_platok8", "", 50, ""},
          //
          { "V12_LUNETTE_BLANCHE", "Designer Glasses Blanche", 25000, ""},
          { "V12_LUNETTE_BLEU", "Designer Glasses Bleu", 25000, ""},
          { "V12_LUNETTE", "Designer Glasses Lunette", 25000, ""},
          { "V12_LUNETTE_ROUGE", "Designer Glasses Rogue", 25000, ""},
          { "V12_LUNETTE_VERSACE", "Designer Glasses Versace", 25000, ""},
          //
          { "V12_BREITLING5", "Designer Watch 1", 50000, ""},
          { "V12_BREITLING4", "Designer Watch 2", 50000, ""},
          { "V12_BREITLING", "Designer Watch 3", 50000, ""},
          { "V12_BREITLING1", "Designer Watch 4", 50000, ""},
          { "V12_BREITLING6", "Designer Watch 5", 50000, ""},
          { "V12_BREITLING3", "Designer Watch 6", 50000, ""},
          { "V12_BREITLING2", "Designer Watch 7", 50000, ""},
          { "V12_HAUREX", "Designer Bling 1", 50000, ""},
          { "V12_HUBLOT", "Designer Bling 2", 50000, ""},
          { "V12_ROLEX", "Designer Bling 3", 50000, ""},
          { "V12_BLUNT", "Designer Bling 4", 50000, ""},
          { "V12_CHAINE_ARGENTER", "Designer Bling 5", 50000, ""},
          { "V12_CHAINE", "Designer Bling 6", 50000, ""},
          { "V12_FEFE", "Designer Bling 7", 50000, ""},
          { "V12_ILLU", "Designer Bling 8", 50000, ""},
          { "V12_LAMBO", "Designer Bling 9", 50000, ""},
          { "V12_VERSACE1", "Designer Bling 10", 50000, ""},
          { "V12_PORSCHE", "Designer Bling 11", 50000, ""},
          { "V12_RAIDERS", "Designer Bling 12", 50000, ""},
          { "V12_CHAINE2", "Designer Bling 13", 50000, ""},
          { "V12_VERSACE", "Designer Bling 14", 50000, { "", "", -1 } }
        };
        vests[] = {
          { "NONE", "Remove Vest", 0, ""},	  
          { "k_cut_1", "", 50, ""},
          { "k_cut_2", "", 50, ""},
          { "k_cut_3", "", 50, ""},
          { "k_cut_4", "", 50, ""},
          { "k_cut_5", "", 50, ""},
          { "k_cut_6", "", 50, ""},
          { "k_cut_7", "", 50, ""},
          { "k_cut_8", "", 50, ""},
          { "k_cut_10", "", 50, ""},
          { "k_cut_11", "", 50, ""},
          { "k_cut_12", "", 50, ""},
          { "k_cut_13", "", 50, ""},
          { "k_cut_14", "", 50, ""},
          { "k_cut_15", "", 50, ""},
          { "k_cut_16", "", 50, { "", "", -1 } }
        };
        backpacks[] = {
          { "NONE", "Remove Backpack", 0, ""},
          { "bag_like", "", 1000, ""},
          { "bag_like_red", "", 1000, ""},
          { "bag_like_blue", "", 1000, { "", "", -1 } }
        };
    };

    class burglary {
        title = "STR_Shops_C_burglary";
        conditions = "";
        side = "civ";
        uniforms[] = {
          { "NONE", $STR_C_Remove_uniforms, 0, "" }
        };
        headgear[] = {
          { "NONE", $STR_C_Remove_headgear, 0, "" },
          { "anzus_CAP_beanie_1", "", 20, "" },
          { "anzus_CAP_berd_003_u_o", "", 20, "" },
          { "anzus_CAP_berd_003_u_u", "", 20, "" },
          { "anzus_CAP_berd_006_u_k", "", 20, "" },
          { "anzus_CAP_Headgear", "", 20, "" },
          { "anzus_CAP_Headgear1", "", 20, "" },
          { "anzus_CAP_Headgear_1", "", 20, "" },
          { "H_Watchcap_blk", "", 20, "" },
          { "kio_skl_msk_black", "", 20, "" },
          { "kio_skl_msk_blood", "", 20, "" },
          { "H_EarProtectors_black_F", "", 20, "" },
          { "H_Construction_headset_orange_F", "", 20, "" },
          { "pop_palestino", "", 20, "" },
          { "H_RacingHelmet_4_F", "", 20, "" },
          { "H_WirelessEarpiece_F", "", 20, "" }
        };
        goggles[] = {
          { "NONE", $STR_C_Remove_goggles, 0, "" },
          { "G_Balaclava_blk", "", 10, "" },
          { "G_Bandanna_aviator", "", 10, "" },
          { "G_Bandanna_khk", "", 10, "" },
          { "G_Balaclava_TI_blk_F", "", 10, "" },
          { "G_Spectacles", "", 10, "" }
        };
        vests[] = {
          { "NONE", $STR_C_Remove_vests, 0, "" }
        };
        backpacks[] = {
          { "NONE", $STR_C_Remove_backpacks, 0, "" },
          { "B_AssaultPack_blk", "", 100, "" },
          { "anzus_backpack_b", "", 100, "" },
          { "anzus_backpack_a", "", 100, "" },
          { "anzus_backpack_d", "", 100, "" },
          { "anzus_backpack_j", "", 100, "" },
          { "JD_Bag", "", 28000, "" }
        };
    };
};
